Kinetis E Peripheral Drivers: CAN APIs Specification
CAN APIs Specification
CAN Driver
Functions
void CAN_Init (MSCAN_Type *pCANx, MSCAN_ConfigPtr pCANConfig)
Initialize MSCAN module.
uint8_t CAN_DeInit (MSCAN_Type *pCANx)
Denitialize MSCAN module.
uint8_t CAN_EnterSleep (MSCAN_Type *pCANx)
MSCAN enter into sleep mode.
uint8_t CAN_WakeUpFromSleep (MSCAN_Type *pCANx)
MSCAN wakeup from sleep mode.
uint8_t CAN_LaunchInitialRequest (MSCAN_Type *pCANx)
launch the CAN initialization mode request
uint8_t CAN_LoadOneFrameToBuff (MSCAN_Type *pCANx, MSCAN_RegisterFramePtr pFrameBuff)
Write a frame data to transmitter buff.
uint8_t CAN_ReadOneFrameFromBuff (MSCAN_Type *pCANx, MSCAN_FramePtr pRxFrame)
read a frame data from receiver buffer
void MSCAN_SetRxCallBack (MSCAN_CallbackType pCallBack)
set receive call back function for MSCAN module.
void MSCAN_SetTxCallBack (MSCAN_CallbackType pCallBack)
set transmitting call back function for MSCAN module.
__STATIC_INLINE uint8_t CAN_IsRxFrameFlag (MSCAN_Type *pCANx)
Check Received Frame Flag.
__STATIC_INLINE uint8_t CAN_IsReceiving (MSCAN_Type *pCANx)
Check Receiver Active Status.
__STATIC_INLINE uint8_t CAN_IsSynToBus (MSCAN_Type *pCANx)
Check CAN Synchronized Status.
__STATIC_INLINE void CAN_SleepModeReq (MSCAN_Type *pCANx)
Sleep Mode Request.
__STATIC_INLINE void CAN_InitialModeReq (MSCAN_Type *pCANx)
Initialization Mode Request.
__STATIC_INLINE void CAN_NormalModeReq (MSCAN_Type *pCANx)
Normal Mode Request.
__STATIC_INLINE void CAN_LoopModeEn (MSCAN_Type *pCANx)
Loopback Self Test Mode Enable.
__STATIC_INLINE void CAN_LoopModeDisable (MSCAN_Type *pCANx)
Loopback Self Test Mode Disable.
__STATIC_INLINE void CAN_ListenModeEn (MSCAN_Type *pCANx)
Listen Only Mode Enable.
__STATIC_INLINE void CAN_ListenModeDisable (MSCAN_Type *pCANx)
Listen Only Mode Disable.
__STATIC_INLINE void CAN_BusOffUserRecovery (MSCAN_Type *pCANx)
Bus-Off Recovery Mode - user request.
__STATIC_INLINE void CAN_BusOffAutoRecovery (MSCAN_Type *pCANx)
Bus-Off Recovery Mode - Auto.
__STATIC_INLINE uint8_t CAN_IsSleepMode (MSCAN_Type *pCANx)
Check Sleep Mode Acknowledge.
__STATIC_INLINE uint8_t CAN_IsInitialMode (MSCAN_Type *pCANx)
Check Initialization Mode Acknowledge.
__STATIC_INLINE uint8_t CAN_IsWakeUpIntFlag (MSCAN_Type *pCANx)
Check Wake-Up Interrupt Flag.
__STATIC_INLINE uint8_t CAN_IsStatusChangeFlag (MSCAN_Type *pCANx)
Check CAN Status Change Interrupt Flag.
__STATIC_INLINE uint8_t CAN_IsOverRunFlag (MSCAN_Type *pCANx)
Check Overrun Interrupt Flag.
__STATIC_INLINE uint8_t CAN_IsRxBuffFull (MSCAN_Type *pCANx)
Check Receive Buffer Full Flag.
__STATIC_INLINE uint8_t CAN_GetReceiverStatus (MSCAN_Type *pCANx)
Get Receiver Status.
__STATIC_INLINE uint8_t CAN_GetTransmitterStatus (MSCAN_Type *pCANx)
Get Transmitter Status.
__STATIC_INLINE uint8_t CAN_GetTransmitterBufferEmptyFlag (MSCAN_Type *pCANx)
Get Transmitter Buffer Empty Flag.
__STATIC_INLINE void CAN_TransmitterEmptyIntEn (MSCAN_Type *pCANx)
Transmitter Empty Interrupt Enable.
__STATIC_INLINE void CAN_TransmitterEmptyIntDisable (MSCAN_Type *pCANx)
Transmitter Empty Interrupt Disable.
__STATIC_INLINE void CAN_WriteAbortRequestReg (MSCAN_Type *pCANx, uint8_t u8AbortRequest)
Write Abort Request Register.
__STATIC_INLINE uint8_t CAN_GetAbortFlag (MSCAN_Type *pCANx)
Get Abort Acknowledge.
__STATIC_INLINE void CAN_TxBuffSelect (MSCAN_Type *pCANx, uint8_t u8TxBuff)
Transmit Buffer Select - The lowest numbered bit places the respective transmit buffer in the CANTXFG register space.
__STATIC_INLINE uint8_t CAN_GetTxBuffSelect (MSCAN_Type *pCANx)
Get the selected transmitter buffer.
__STATIC_INLINE void CAN_IDAcceptMode (MSCAN_Type *pCANx, uint8_t u8IDAcceptMode)
Set Identifier Acceptance Mode.
__STATIC_INLINE uint8_t CAN_IDAcceptHit (MSCAN_Type *pCANx)
Set Identifier Acceptance Hit Indicator.
__STATIC_INLINE uint8_t CAN_IsBusOff (MSCAN_Type *pCANx)
Check if is Bus-Off Status.
__STATIC_INLINE uint8_t CAN_GetReceiveErrorCount (MSCAN_Type *pCANx)
Get Receive Error Counter.
__STATIC_INLINE void CAN_Enable (MSCAN_Type *pCANx)
CAN enable.
__STATIC_INLINE void CAN_Disable (MSCAN_Type *pCANx)
CAN disable.
__STATIC_INLINE void CAN_WakeUpIntEn (MSCAN_Type *pCANx)
WakeUp Interrupt Enable.
__STATIC_INLINE void CAN_WakeUpIntDisable (MSCAN_Type *pCANx)
WakeUp Interrupt Disable.
__STATIC_INLINE void CAN_StatusChangeIntEn (MSCAN_Type *pCANx)
CAN Status Change Interrupt Enable.
__STATIC_INLINE void CAN_StatusChangeIntDisable (MSCAN_Type *pCANx)
CAN Status Change Interrupt Disable.
__STATIC_INLINE void CAN_ReceiverStatusChangeIntEn (MSCAN_Type *pCANx)
Receiver Status Change Enable.
__STATIC_INLINE void CAN_ReceiverStatusChangeIntDisable (MSCAN_Type *pCANx)
CAN Receiver Status Change Disable.
__STATIC_INLINE void CAN_TransmitterStatusChangeIntEn (MSCAN_Type *pCANx)
Transmitter Status Change Enable.
__STATIC_INLINE void CAN_TransmitterStatusChangeIntDisable (MSCAN_Type *pCANx)
Transmitter Status Change Disable.
__STATIC_INLINE void CAN_OverrunIntEn (MSCAN_Type *pCANx)
Overrun Interrupt Enable.
__STATIC_INLINE void CAN_OverrunIntDisable (MSCAN_Type *pCANx)
Overrun Interrupt Disable.
__STATIC_INLINE void CAN_ReceiverFullIntEn (MSCAN_Type *pCANx)
Receiver Full Interrupt Enable.
__STATIC_INLINE void CAN_ReceiverFullIntDisable (MSCAN_Type *pCANx)
Receiver Full Interrupt Disable.
__STATIC_INLINE void CAN_TimerEn (MSCAN_Type *pCANx)
Timer Enable.
__STATIC_INLINE void CAN_TimerDisable (MSCAN_Type *pCANx)
Timer Disable.
__STATIC_INLINE void CAN_StopInWaitModeEn (MSCAN_Type *pCANx)
CAN Stops in Wait Mode Enable.
__STATIC_INLINE void CAN_StopInWaitModeDisable (MSCAN_Type *pCANx)
CAN Stops in Wait Mode Disable.
__STATIC_INLINE void CAN_WakeUpEn (MSCAN_Type *pCANx)
WakeUp Enable.
__STATIC_INLINE void CAN_WakeUpDisable (MSCAN_Type *pCANx)
WakeUp Disable.
__STATIC_INLINE void CAN_WakeUpModeFilter (MSCAN_Type *pCANx)
MSCAN wakes up only in case of a dominant pulse on the CAN bus that has a length of Twup.
__STATIC_INLINE void CAN_WakeUpModeNoFilter (MSCAN_Type *pCANx)
MSCAN wakes up on any dominant level on the CAN bus.
__STATIC_INLINE void CAN_WriteIDAR0Reg (MSCAN_Type *pCANx, uint8_t *pID)
write MSCAN Identifier Acceptance Register n of First Bank
__STATIC_INLINE void CAN_WriteIDAR1Reg (MSCAN_Type *pCANx, uint8_t *pID)
write MSCAN Identifier Acceptance Register n of Second Bank
__STATIC_INLINE void CAN_WriteIDAM0Reg (MSCAN_Type *pCANx, uint8_t *pID)
write MSCAN Identifier Mask Register n of First Bank
__STATIC_INLINE void CAN_SetBaudRateReg (MSCAN_Type *pCANx, MSCAN_BaudRateSettingType sBspSetting)
write MSCAN Bus Timming Register
__STATIC_INLINE void CAN_WriteIDAM1Reg (MSCAN_Type *pCANx, uint8_t *pID)
write MSCAN Identifier Mask Register n of Second Bank
__STATIC_INLINE void CAN_LaunchTransmitBuffer (MSCAN_Type *pCANx, uint8_t TxBuffer)
Clear Transmitter Buffer Empty Flag to schedule for transmission.
__STATIC_INLINE void CAN_WriteTEIDR0Reg (MSCAN_Type *pCANx, uint8_t ucBuffer)
Write Transmit Extended and Standard Identifier Register 0.
__STATIC_INLINE void CAN_WriteTEIDR1Reg (MSCAN_Type *pCANx, uint8_t ucBuffer)
Write Transmit Extended Identifier Register 1.
__STATIC_INLINE void CAN_WriteTEIDR2Reg (MSCAN_Type *pCANx, uint8_t ucBuffer)
Write Transmit Extended Identifier Register 2.
__STATIC_INLINE void CAN_WriteTEIDR3Reg (MSCAN_Type *pCANx, uint8_t ucBuffer)
Write Transmit Extended Identifier Register 3.
__STATIC_INLINE void CAN_WriteTSIDR1Reg (MSCAN_Type *pCANx, uint8_t ucBuffer)
Write Transmit Standard Identifier Register 1.
__STATIC_INLINE uint8_t CAN_ReadIDR1Reg (MSCAN_Type *pCANx)
Read receiver extend and standard identifier register 1.
__STATIC_INLINE uint8_t CAN_ReadIDR0Reg (MSCAN_Type *pCANx)
Read receiver extend and standard identifier register 0.
__STATIC_INLINE uint8_t CAN_ReadIDR2Reg (MSCAN_Type *pCANx)
Read receiver extend identifier register 2.
__STATIC_INLINE uint8_t CAN_ReadIDR3Reg (MSCAN_Type *pCANx)
Read receiver extend identifier register 3.
__STATIC_INLINE uint8_t CAN_ReadRTSRHReg (MSCAN_Type *pCANx)
Read receiver stamps registers high bytes.
__STATIC_INLINE uint8_t CAN_ReadRTSRLReg (MSCAN_Type *pCANx)
Read receiver stamps registers low bytes.
__STATIC_INLINE uint8_t CAN_ReadTTSRHReg (MSCAN_Type *pCANx)
Read transmitter stamps registers high byte.
__STATIC_INLINE uint8_t CAN_ReadTTSRLReg (MSCAN_Type *pCANx)
Read transmitter stamps registers low byte.
__STATIC_INLINE void CAN_ClearWUPIF_Flag (MSCAN_Type *pCANx)
Clear Wake-Up Interrupt Flag.
__STATIC_INLINE void CAN_ClearCSCIF_Flag (MSCAN_Type *pCANx)
Clear CAN Status Change Interrupt Flag.
__STATIC_INLINE void CAN_ClearOVRIF_Flag (MSCAN_Type *pCANx)
Clear Overrun Interrupt Flag.
__STATIC_INLINE void CAN_ClearRXF_Flag (MSCAN_Type *pCANx)
Clear Receive Buffer Full Flag.
__STATIC_INLINE void CAN_ClearRXFRM_Flag (MSCAN_Type *pCANx)
Clear Received Frame Flag.
__STATIC_INLINE void CAN_ClearSLPRQ_Flag (MSCAN_Type *pCANx)
Clear Sleep Mode Request.
__STATIC_INLINE void CAN_SetIDAMode (MSCAN_Type *pCANx, uint8_t IDAMode)
Identifier Acceptance Mode.
void MSCAN_RxIsr (void)
MSCAN Receive interrupt service routine.
void MSCAN_TxIsr (void)
MSCAN transmitting interrupt service routine.
uint8_t CAN_SendItemToBuffer (MSCAN_Type *pCANx, ItemInfoPtr pTxItemInfo, FrameBufferInfoPtr pTxBuffInfo)
Write a frame data to buffers.
uint8_t CAN_TransmitItemByInt (MSCAN_Type *pCANx, ItemInfoPtr pTxItemInfo, FrameBufferInfoPtr pTxBuffInfo)
Write a frame data to buffers.
uint8_t CAN_CheckSendBufferFrame (MSCAN_Type *pCANx, FrameBufferInfoPtr pTxBuffInfo)
Check buffer status and send data frame to transmitting buffer of MSCAN.
uint8_t CAN_ReadOneFramefromBufferQueue (MSCAN_FramePtr pRxFrameInfo)
Check buffer status and receive data frame from receiver buffer of MSCAN.
void MSCAN_GlobeVaribleInit (MSCAN_Type *pCANx)
Initialize the globe variable for CAN buffer and buffer Queue.
void MSCAN_TxProcessing (void)
MSCAN Transmitting Callback function.
void MSCAN_RxProcessing (void)
MSCAN receiving Callback function.
Variables
uint16_t bStopEn:1
uint16_t bTimerEn:1
uint16_t bWakeUpEn:1
uint16_t bCanEn:1
uint16_t bCLKSRC:1
uint16_t bLoopModeEn:1
uint16_t bWUPM:1
uint16_t bListenModeEn:1
uint16_t bWakeUpIEn:1
uint16_t bStatusChangeIEn:1
uint16_t bRxStatusChangeIEn:1
uint16_t bTxStatusChangeIEn:1
uint16_t bOverRunIEn:1
uint16_t bRxFullIEn:1
uint16_t bTxEmptyIEn:1
uint16_t bBusOffUser:1
uint16_t SJW:2
uint16_t BRP:6
uint16_t SAMP:1
uint16_t TSEG2:3
uint16_t TSEG1:4
MSCAN_SettingType sSetting
MSCAN_BaudRateSettingType sBaudRateSetting
uint8_t u8IDARMode
uint8_t u8IDARHit
uint32_t u32IDAR0
uint32_t u32IDAR1
uint32_t u32IDMR0
uint32_t u32IDMR1
uint8_t EID17_15:3
uint8_t R_TEIDE:1
uint8_t R_TSRR:1
uint8_t EID20_18_OR_SID2_0:3
uint8_t ERTR:1
uint8_t EID6_0:7
MSCAN_IDR1Type IDR1
MSCAN_IDR3Type IDR3
uint8_t Bytes
uint32_t EID6_0:7
uint32_t EID14_7:8
uint32_t EID17_15:3
uint32_t EID20_18:3
uint32_t EID28_21:8
uint32_t EID2_0:3
uint32_t EID10_3:8
MSCAN_StandardIDType StandID
MSCAN_ExtendIDType ExtID
uint32_t ID
union {
MSCAN_StandardIDType StandID
MSCAN_ExtendIDType ExtID
uint32_t ID
} ID_Type
uint8_t DSR [8]
uint8_t DLR
uint8_t BPR
uint8_t bIsRemoteFrame
uint8_t bIsExtOrStand
uint8_t u8TSRH
uint8_t u8TSRL
uint8_t EIDR0
uint8_t EIDR1
uint8_t EIDR2
uint8_t EIDR3
uint8_t EDSR [8]
uint8_t DLR
uint8_t BPR
uint8_t TSRH
uint8_t TSRL
Detailed Description
This section defines the exact usage for each API function and macro.
Function Documentation
void CAN_Init (MSCAN_Type * pCANx, MSCAN_ConfigPtr pCANConfig)
Parameters
[in] pCANx point to CAN module type.
[in] pCANConfig point to CAN configure structure.
Returns
none
@ Pass/ Fail criteria: none
References MSCAN_SettingType::bBusOffUser, MSCAN_SettingType::bCanEn, MSCAN_SettingType::bCLKSRC, MSCAN_SettingType::bListenModeEn, MSCAN_SettingType::bLoopModeEn, MSCAN_SettingType::bOverRunIEn, MSCAN_SettingType::bRxFullIEn, MSCAN_SettingType::bRxStatusChangeIEn, MSCAN_SettingType::bStatusChangeIEn, MSCAN_SettingType::bStopEn, MSCAN_SettingType::bTimerEn, MSCAN_SettingType::bTxEmptyIEn, MSCAN_SettingType::bTxStatusChangeIEn, MSCAN_SettingType::bWakeUpEn, MSCAN_SettingType::bWakeUpIEn, MSCAN_SettingType::bWUPM, CAN_BusOffAutoRecovery(), CAN_BusOffUserRecovery(), CAN_Enable(), CAN_InitialModeReq(), CAN_IsInitialMode(), CAN_ListenModeDisable(), CAN_ListenModeEn(), CAN_LoopModeDisable(), CAN_LoopModeEn(), CAN_NormalModeReq(), CAN_OverrunIntDisable(), CAN_OverrunIntEn(), CAN_ReceiverFullIntDisable(), CAN_ReceiverFullIntEn(), CAN_ReceiverStatusChangeIntDisable(), CAN_ReceiverStatusChangeIntEn(), CAN_SetBaudRateReg(), CAN_SetIDAMode(), CAN_StatusChangeIntDisable(), CAN_StatusChangeIntEn(), CAN_StopInWaitModeDisable(), CAN_StopInWaitModeEn(), CAN_TimerDisable(), CAN_TimerEn(), CAN_TransmitterEmptyIntDisable(), CAN_TransmitterEmptyIntEn(), CAN_TransmitterStatusChangeIntDisable(), CAN_TransmitterStatusChangeIntEn(), CAN_WakeUpDisable(), CAN_WakeUpEn(), CAN_WakeUpIntDisable(), CAN_WakeUpIntEn(), CAN_WakeUpModeFilter(), CAN_WakeUpModeNoFilter(), CAN_WriteIDAM0Reg(), CAN_WriteIDAM1Reg(), CAN_WriteIDAR0Reg(), CAN_WriteIDAR1Reg(), MSCAN_ConfigType::sBaudRateSetting, MSCAN_ConfigType::sSetting, MSCAN_ConfigType::u32IDAR0, MSCAN_ConfigType::u32IDAR1, MSCAN_ConfigType::u32IDMR0, MSCAN_ConfigType::u32IDMR1, and MSCAN_ConfigType::u8IDARMode.
uint8_t CAN_DeInit (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
[in] pCANConfig point to CAN configure structure.
Returns
status
@ Pass/ Fail criteria: none
References CAN_Disable(), and CAN_LaunchInitialRequest().
uint8_t CAN_EnterSleep (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
fail or success
@ Pass/ Fail criteria: none
References CAN_ClearWUPIF_Flag(), CAN_IsInitialMode(), CAN_IsWakeUpIntFlag(), CAN_SleepModeReq(), CAN_WakeUpEn(), and CAN_WakeUpIntEn().
uint8_t CAN_WakeUpFromSleep (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
fail or success
@ Pass/ Fail criteria: none
References CAN_ClearSLPRQ_Flag(), and CAN_IsSleepMode().
uint8_t CAN_LaunchInitialRequest (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
fail or success
@ Pass/ Fail criteria: none
References CAN_InitialModeReq(), and CAN_IsInitialMode().
uint8_t CAN_LoadOneFrameToBuff (MSCAN_Type * pCANx, MSCAN_RegisterFramePtr pFrameBuff)
Parameters
[in] pCANx point to CAN module type.
[in] pFrameBuff point to CAN frame buffer.
Returns
send status, fail or success
@ Pass/ Fail criteria: none
References CAN_GetTransmitterBufferEmptyFlag(), CAN_GetTxBuffSelect(), CAN_LaunchTransmitBuffer(), CAN_TxBuffSelect(), and TRANSMITTER_TX_NO_EMPTY.
uint8_t CAN_ReadOneFrameFromBuff (MSCAN_Type * pCANx, MSCAN_FramePtr pRxFrame)
Parameters
[in] pCANx point to CAN module type.
Returns
send status, fail or success
@ Pass/ Fail criteria: none
References MSCAN_FrameType::bIsExtOrStand, MSCAN_FrameType::bIsRemoteFrame, IDR1_3_UNION::Bytes, CAN_ClearRXF_Flag(), CAN_IsRxBuffFull(), CAN_ReadIDR0Reg(), CAN_ReadIDR1Reg(), CAN_ReadIDR2Reg(), CAN_ReadIDR3Reg(), CAN_ReadTTSRHReg(), CAN_ReadTTSRLReg(), MSCAN_FrameType::DLR, MSCAN_FrameType::DSR, MSCAN_ExtendIDType::EID14_7, MSCAN_IDR1Type::EID17_15, MSCAN_ExtendIDType::EID17_15, MSCAN_ExtendIDType::EID20_18, MSCAN_IDR1Type::EID20_18_OR_SID2_0, MSCAN_ExtendIDType::EID28_21, MSCAN_IDR3Type::EID6_0, MSCAN_ExtendIDType::EID6_0, MSCAN_IDR3Type::ERTR, MSCAN_FrameType::ExtID, MSCAN_FrameType::ID_Type, IDR1_3_UNION::IDR1, IDR1_3_UNION::IDR3, MSCAN_IDR1Type::R_TEIDE, MSCAN_FrameType::u8TSRH, and MSCAN_FrameType::u8TSRL.
void MSCAN_SetRxCallBack (MSCAN_CallbackType pCallBack)
Parameters
[in] pCallBack point to address of MSCAN call back function.
Returns
none.
@ Pass/ Fail criteria: none.
void MSCAN_SetTxCallBack (MSCAN_CallbackType pCallBack)
Parameters
[in] pCallBack point to address of MSCAN call back function.
Returns
none.
@ Pass/ Fail criteria: none.
__STATIC_INLINE uint8_t CAN_IsRxFrameFlag (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
Received Frame Flag
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t CAN_IsReceiving (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
Receiver Active Status
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t CAN_IsSynToBus (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
Synchronized Status
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_SleepModeReq (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_InitialModeReq (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_NormalModeReq (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_LoopModeEn (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_LoopModeDisable (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_ListenModeEn (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_ListenModeDisable (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_BusOffUserRecovery (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_BusOffAutoRecovery (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t CAN_IsSleepMode (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
Sleep Mode Acknowledge
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t CAN_IsInitialMode (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
Initialization Mode Acknowledge
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t CAN_IsWakeUpIntFlag (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
Wake-Up Interrupt Flag
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t CAN_IsStatusChangeFlag (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
CAN Status Change Interrupt Flag
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t CAN_IsOverRunFlag (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
Overrun Interrupt Flag
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t CAN_IsRxBuffFull (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
Overrun Interrupt Flag
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t CAN_GetReceiverStatus (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
Receiver Status
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t CAN_GetTransmitterStatus (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
Transmitter Status
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t CAN_GetTransmitterBufferEmptyFlag (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
Transmitter Buffer Empty Flag
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_TransmitterEmptyIntEn (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_TransmitterEmptyIntDisable (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_WriteAbortRequestReg (MSCAN_Type * pCANx, uint8_t u8AbortRequest)
Parameters
[in] pCANx point to CAN module type.
[in] u8AbortRequest abort request to tx buffer.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t CAN_GetAbortFlag (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
Abort Acknowledge
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_TxBuffSelect (MSCAN_Type * pCANx, uint8_t u8TxBuff)
Parameters
[in] pCANx point to CAN module type.
[in] u8TxBuff tx buff to be selected.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t CAN_GetTxBuffSelect (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_IDAcceptMode (MSCAN_Type * pCANx, uint8_t u8IDAcceptMode)
Parameters
[in] pCANx point to CAN module type.
[in] u8IDAcceptMode Identifier Acceptance Mode.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t CAN_IDAcceptHit (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
[in] u8IDAcceptHit Identifier Acceptance Hit Indicator.
Returns
filter number for hit
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t CAN_IsBusOff (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
Bus-Off Status
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t CAN_GetReceiveErrorCount (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
Receive Error Counter
@ Pass/ Fail criteria: This field is read only in sleep mode (SLPRQ = 1 and SLPAK = 1) or initialization mode (INITRQ = 1 and INITAK = 1)
__STATIC_INLINE void CAN_Enable (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_Disable (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_WakeUpIntEn (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_WakeUpIntDisable (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_StatusChangeIntEn (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_StatusChangeIntDisable (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_ReceiverStatusChangeIntEn (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_ReceiverStatusChangeIntDisable (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_TransmitterStatusChangeIntEn (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_TransmitterStatusChangeIntDisable (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_OverrunIntEn (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_OverrunIntDisable (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_ReceiverFullIntEn (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_ReceiverFullIntDisable (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_TimerEn (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_TimerDisable (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_StopInWaitModeEn (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_StopInWaitModeDisable (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_WakeUpEn (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_WakeUpDisable (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_WakeUpModeFilter (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_WakeUpModeNoFilter (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_WriteIDAR0Reg (MSCAN_Type * pCANx, uint8_t * pID)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_WriteIDAR1Reg (MSCAN_Type * pCANx, uint8_t * pID)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_WriteIDAM0Reg (MSCAN_Type * pCANx, uint8_t * pID)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_SetBaudRateReg (MSCAN_Type * pCANx, MSCAN_BaudRateSettingType sBspSetting)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
References MSCAN_BaudRateSettingType::BRP, MSCAN_BaudRateSettingType::SAMP, MSCAN_BaudRateSettingType::SJW, MSCAN_BaudRateSettingType::TSEG1, and MSCAN_BaudRateSettingType::TSEG2.
__STATIC_INLINE void CAN_WriteIDAM1Reg (MSCAN_Type * pCANx, uint8_t * pID)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_LaunchTransmitBuffer (MSCAN_Type * pCANx, uint8_t TxBuffer)
Parameters
[in] pCANx point to CAN module type.
[in] TxBuffer point to CAN transmitter buffer to be launched.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_WriteTEIDR0Reg (MSCAN_Type * pCANx, uint8_t ucBuffer)
Parameters
[in] pCANx point to CAN module type.
[in] ucBuffer the data written to IDR0 register.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_WriteTEIDR1Reg (MSCAN_Type * pCANx, uint8_t ucBuffer)
Parameters
[in] pCANx point to CAN module type.
[in] ucBuffer the data written to TEIDR1 register.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_WriteTEIDR2Reg (MSCAN_Type * pCANx, uint8_t ucBuffer)
Parameters
[in] pCANx point to CAN module type.
[in] ucBuffer the data written to TEIDR2 register.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_WriteTEIDR3Reg (MSCAN_Type * pCANx, uint8_t ucBuffer)
Parameters
[in] pCANx point to CAN module type.
[in] ucBuffer the data written to TEIDR3 register.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_WriteTSIDR1Reg (MSCAN_Type * pCANx, uint8_t ucBuffer)
Parameters
[in] pCANx point to CAN module type.
[in] ucBuffer the data written to TSID1 register.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t CAN_ReadIDR1Reg (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
REIDR0 or RSIDR0
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t CAN_ReadIDR0Reg (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
REIDR1 or RSIDR1
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t CAN_ReadIDR2Reg (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
REIDR2
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t CAN_ReadIDR3Reg (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
REIDR3
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t CAN_ReadRTSRHReg (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
RTSRH
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t CAN_ReadRTSRLReg (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
RTSRL
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t CAN_ReadTTSRHReg (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
TTSRH
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t CAN_ReadTTSRLReg (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
TTSRL
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_ClearWUPIF_Flag (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_ClearCSCIF_Flag (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_ClearOVRIF_Flag (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_ClearRXF_Flag (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_ClearRXFRM_Flag (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_ClearSLPRQ_Flag (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void CAN_SetIDAMode (MSCAN_Type * pCANx, uint8_t IDAMode)
Parameters
[in] pCANx point to CAN module type.
Returns
none
@ Pass/ Fail criteria: none
void MSCAN_RxIsr (void)
Parameters
@return none
@ Pass/ Fail criteria: none
void MSCAN_TxIsr (void)
Parameters
@return none
@ Pass/ Fail criteria: none
uint8_t CAN_SendItemToBuffer (MSCAN_Type * pCANx, ItemInfoPtr pTxItemInfo, FrameBufferInfoPtr pTxBuffInfo)
Parameters
[in] pCANx point to CAN module type.
[in] pTxItemInfo point to CAN transmitting data information
[in] pTxBuffInfo point to CAN transmitting Buffer information
Returns
send status, fail or success
@ Pass/ Fail criteria: none
References ItemInfoType::bIsRemoteFrame, MSCAN_RegisterFrameType::BPR, IDR1_3_UNION::Bytes, CAN_BUFFER_LENGTH, MSCAN_RegisterFrameType::DLR, MSCAN_RegisterFrameType::EDSR, MSCAN_ExtendIDType::EID14_7, MSCAN_IDR1Type::EID17_15, MSCAN_ExtendIDType::EID17_15, MSCAN_ExtendIDType::EID20_18, MSCAN_IDR1Type::EID20_18_OR_SID2_0, MSCAN_ExtendIDType::EID28_21, MSCAN_IDR3Type::EID6_0, MSCAN_ExtendIDType::EID6_0, MSCAN_RegisterFrameType::EIDR0, MSCAN_RegisterFrameType::EIDR1, MSCAN_RegisterFrameType::EIDR2, MSCAN_RegisterFrameType::EIDR3, MSCAN_IDR3Type::ERTR, IDR1_3_UNION::IDR1, IDR1_3_UNION::IDR3, MSCAN_IDR1Type::R_TEIDE, MSCAN_IDR1Type::R_TSRR, and ItemInfoType::u8BPR.
uint8_t CAN_TransmitItemByInt (MSCAN_Type * pCANx, ItemInfoPtr pTxItemInfo, FrameBufferInfoPtr pTxBuffInfo)
Parameters
[in] pCANx point to CAN module type.
[in] pTxItemInfo point to CAN transmitting data information
[in] pTxBuffInfo point to CAN transmitting Buffer information
Returns
none
@ Pass/ Fail criteria: none
References CAN_SendItemToBuffer(), and CAN_TransmitterEmptyIntEn().
uint8_t CAN_CheckSendBufferFrame (MSCAN_Type * pCANx, FrameBufferInfoPtr pTxBuffInfo)
Parameters
[in] pCANx point to CAN module type.
[in] pTxBuffInfo point to CAN transmitting Buffer information
Returns
false- no buffer transmitted, true -transmitting is busy
@ Pass/ Fail criteria: none
References CAN_BUFFER_LENGTH, and CAN_LoadOneFrameToBuff().
uint8_t CAN_ReadOneFramefromBufferQueue (MSCAN_FramePtr pRxFrameInfo)
Parameters
[in] pTxBuffInfo point to CAN transmitting Buffer information
Returns
false- no buffer transmitted, true -transmitting is busy
@ Pass/ Fail criteria: none
References CAN_BUFFER_LENGTH.
void MSCAN_GlobeVaribleInit (MSCAN_Type * pCANx)
Parameters
[in] pCANx point to CAN module type.
Returns
none.
@ Pass/ Fail criteria: none.
References CAN_BUFFER_LENGTH, MSCAN_RxProcessing(), MSCAN_SetRxCallBack(), MSCAN_SetTxCallBack(), and MSCAN_TxProcessing().
void MSCAN_TxProcessing (void)
Parameters
@return none
@ Pass/ Fail criteria: none
References CAN_CheckSendBufferFrame(), CAN_ClearCSCIF_Flag(), CAN_ClearOVRIF_Flag(), CAN_ClearWUPIF_Flag(), CAN_GetReceiveErrorCount(), CAN_GetReceiverStatus(), CAN_IsOverRunFlag(), CAN_IsStatusChangeFlag(), CAN_IsWakeUpIntFlag(), and CAN_TransmitterEmptyIntDisable().
void MSCAN_RxProcessing (void)
Parameters
@return none
@ Pass/ Fail criteria: none
References CAN_BUFFER_LENGTH, CAN_ClearRXF_Flag(), CAN_IsRxBuffFull(), and CAN_ReadOneFrameFromBuff().
Variable Documentation
uint16_t bStopEn
1: The module ceases to be clocked during wait mode.
uint16_t bTimerEn
Enable internal MSCAN timer for timer stamp
uint16_t bWakeUpEn
MSCAN wake up enable
uint16_t bCanEn
MSCAN Enable
uint16_t bCLKSRC
MSCAN Clock Source, bus clock or oscillator clock
uint16_t bLoopModeEn
Loopback Self Test Mode
uint16_t bWUPM
WakeUp Mode
uint16_t bListenModeEn
enable Listen Only Mode
uint16_t bWakeUpIEn
WakeUp Interrupt Enable
uint16_t bStatusChangeIEn
CAN Status Change Interrupt Enable
uint16_t bRxStatusChangeIEn
CAN receive Status Change Interrupt Enable
uint16_t bTxStatusChangeIEn
CAN transmitter Status Change Interrupt Enable
uint16_t bOverRunIEn
Overrun Interrupt Enable
uint16_t bRxFullIEn
Receiver Full Interrupt Enable
uint16_t bTxEmptyIEn
Transmitter Empty Interrupt Enable
uint16_t bBusOffUser
Bus off recovery mode, 1 - user, 0 - Auto
uint16_t SJW
Synchronization Jump Width.
uint16_t BRP
Baud Rate Prescaler.
uint16_t SAMP
Sampling.
uint16_t TSEG2
Time Segment 2.
uint16_t TSEG1
Time Segment 1.
MSCAN_SettingType sSetting
can setting structure
MSCAN_BaudRateSettingType sBaudRateSetting
can baud rate setting structure
uint8_t u8IDARMode
Set Identifier Acceptance Mode
uint8_t u8IDARHit
Set Identifier Acceptance Hit Indicator
uint32_t u32IDAR0
MSCAN Identifier Acceptance Register n of First Bank
uint32_t u32IDAR1
MSCAN Identifier Acceptance Register n of Second Bank
uint32_t u32IDMR0
MSCAN Identifier Mask Register n of First Bank
uint32_t u32IDMR1
MSCAN Identifier Mask Register n of Second Bank
uint8_t EID17_15
Extended Format Identifier 17-15
uint8_t R_TEIDE
ID Extended
uint8_t R_TSRR
Substitute Remote Request
uint8_t EID20_18_OR_SID2_0
Extended Format Identifier 18-20 or standard format bit 0-2
uint8_t ERTR
Remote Transmission Request
uint8_t EID6_0
Extended Format Identifier 6-0
MSCAN_IDR1Type IDR1
structure for identifier 1
MSCAN_IDR3Type IDR3
structure for identifier 3
uint8_t Bytes
bytes
uint32_t EID6_0
ID[0:6]
uint32_t EID14_7
ID[14:7]
uint32_t EID17_15
ID[17:15]
uint32_t EID20_18
ID[20:18]
uint32_t EID28_21
ID[28:21]
uint32_t EID2_0
ID[0:2]
uint32_t EID10_3
ID[10:3]
MSCAN_StandardIDType StandID
standard format type
MSCAN_StandardIDType StandID
standard format type
MSCAN_ExtendIDType ExtID
extend format type
MSCAN_ExtendIDType ExtID
extend format type
uint32_t ID
Identifire with 32 bit format
uint32_t ID
Identifire with 32 bit format
union { ... } ID_Type
identifier union
uint8_t DSR[8]
data segment
uint8_t DLR
data length
uint8_t BPR
transmit buffer priority
uint8_t bIsRemoteFrame
remote frame or not
uint8_t bIsExtOrStand
extend frame or not
uint8_t u8TSRH
time stamp high byte
uint8_t u8TSRL
time stamp low byte
uint8_t EIDR0
Extended Identifier Register 0
uint8_t EIDR1
Extended Identifier Register 1
uint8_t EIDR2
Extended Identifier Register 2
uint8_t EIDR3
Extended Identifier Register 3
uint8_t EDSR[8]
Extended Data Segment Register
uint8_t DLR
data length field
uint8_t BPR
Buffer Priority Register
uint8_t TSRH
Time Stamp Register High
uint8_t TSRL
Time Stamp Register Low