Kinetis E Peripheral Drivers: RTC API Specification
RTC API Specification
RTC Driver
Functions
void RTC_Init (RTC_ConfigType *pConfig)
inital RTC module
void RTC_SetCallback (RTC_CallbackType pfnCallback)
set call back function for rtc module
void RTC_DeInit (void)
de-initialize rtc module , reset rtc register
__STATIC_INLINE void RTC_EnableInt (void)
enable rtc interrupt.
__STATIC_INLINE void RTC_DisableInt (void)
disable rtc interrupt.
__STATIC_INLINE void RTC_SetModulo (uint16_t u16Mod_Value)
set rtc modulo value.
__STATIC_INLINE void RTC_SetClock (uint16_t u16Clock_Number, uint16_t u16Presalcer)
set rtc clock source and presalcer.
__STATIC_INLINE uint8_t RTC_GetFlags (void)
get rtc flag bit.
__STATIC_INLINE void RTC_ClrFlags (void)
clear rtc flag bit.
Detailed Description
This section specifies the exact usage for each API function and macro.
inline functions
Function Documentation
void RTC_Init (RTC_ConfigType * pConfig)
Parameters
[in] pConfig point to configuration
Returns
none
@ Pass/ Fail criteria: none
References RTC_ConfigType::bClockPresaler, RTC_ConfigType::bClockSource, RTC_ConfigType::bFlag, RTC_ConfigType::bInterruptEn, RTC_ConfigType::bRTCOut, RTC_ClrFlags(), RTC_EnableInt(), RTC_SetClock(), RTC_SetModulo(), and RTC_ConfigType::u16ModuloValue.
void RTC_SetCallback (RTC_CallbackType pfnCallback)
Parameters
[in] pfnCallback point to call back function
Returns
none
@ Pass/ Fail criteria: none
void RTC_DeInit (void)
Parameters
none
Returns
none
@ Pass/ Fail criteria: none
References RTC_ClrFlags(), and RTC_GetFlags().
__STATIC_INLINE void RTC_EnableInt (void)
Parameters
none
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void RTC_DisableInt (void)
Parameters
none
Returns
non
@ Pass/ Fail criteria: none
__STATIC_INLINE void RTC_SetModulo (uint16_t u16Mod_Value)
Parameters
[in] u16Mod_Value
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void RTC_SetClock (uint16_t u16Clock_Number, uint16_t u16Presalcer)
Parameters
[in] u16Clock_Number clock source number
[in] u16Presalcer prescaler value
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t RTC_GetFlags (void)
Parameters
none
Returns
bflag.
@ Pass/ Fail criteria: none
__STATIC_INLINE void RTC_ClrFlags (void)
Parameters
none
Returns
none
@ Pass/ Fail criteria: none