Kinetis E Peripheral Drivers: UART API Specification
UART API Specification
UART Driver
Functions
void UART_Init (UART_Type *pUART, UART_ConfigType *pConfig)
initialize the UART, interrupts disabled, and no hardware flow-control.
uint8_t UART_GetChar (UART_Type *pUART)
receive a character.
void UART_PutChar (UART_Type *pUART, uint8_t u8Char)
send a character.
void UART_SetBaudrate (UART_Type *pUART, UART_ConfigBaudrateType *pConfig)
set baudrate.
void UART_EnableInterrupt (UART_Type *pUART, UART_InterruptType InterruptType)
enable interrupt.
void UART_DisableInterrupt (UART_Type *pUART, UART_InterruptType InterruptType)
disable interrupt.
uint16_t UART_GetFlags (UART_Type *pUART)
get flags from 2 UART status registers.
uint8_t UART_CheckFlag (UART_Type *pUART, UART_FlagType FlagType)
check whether the specified flag is set.
void UART_SendWait (UART_Type *pUART, uint8_t *pSendBuff, uint32_t u32Length)
send a series of charecters using polling mode.
void UART_ReceiveWait (UART_Type *pUART, uint8_t *pReceiveBuff, uint32_t u32Length)
receive a series of charecters using polling mode.
void UART_WaitTxComplete (UART_Type *pUART)
wait tx complete.
void UART_SetCallback (UART_CallbackType pfnCallback)
set up UART callback routines to be called by interrupt service routine.
__STATIC_INLINE uint8_t UART_ReadDataReg (UART_Type *pUART)
read receive buffer
__STATIC_INLINE void UART_WriteDataReg (UART_Type *pUART, uint8_t u8Char)
write transmit buffer
__STATIC_INLINE uint8_t UART_CharPresent (UART_Type *pUART)
check if a character has been received
__STATIC_INLINE void UART_EnableTx (UART_Type *pUART)
enable transmit
__STATIC_INLINE void UART_DisableTx (UART_Type *pUART)
disable transmit
__STATIC_INLINE void UART_EnableRx (UART_Type *pUART)
enable receive
__STATIC_INLINE void UART_DisableRx (UART_Type *pUART)
disable receive
__STATIC_INLINE void UART_EnableLoopback (UART_Type *pUART)
Enable loopback mode.
__STATIC_INLINE void UART_EnableSingleWire (UART_Type *pUART)
enable single wire mode
__STATIC_INLINE void UART_Set8BitMode (UART_Type *pUART)
set 8-bit mode
__STATIC_INLINE void UART_Set9BitMode (UART_Type *pUART)
set 9-bit mode
__STATIC_INLINE void UART_EnableTxBuffEmptyInt (UART_Type *pUART)
enable transmit buffer empty interrupt
__STATIC_INLINE void UART_EnableTxCompleteInt (UART_Type *pUART)
enable transmit complete interrupt
__STATIC_INLINE void UART_EnableRxBuffFullInt (UART_Type *pUART)
enable receive buffer full interrupt
__STATIC_INLINE void UART_DisableTxBuffEmptyInt (UART_Type *pUART)
disable transmit buffer empty interrupt
__STATIC_INLINE void UART_DisableTxCompleteInt (UART_Type *pUART)
disable transmit complete interrupt
__STATIC_INLINE void UART_DisableRxBuffFullInt (UART_Type *pUART)
disable receive buffer full interrupt
__STATIC_INLINE void UART_PutBreak (UART_Type *pUART)
print out break character
__STATIC_INLINE uint8_t UART_IsTxComplete (UART_Type *pUART)
check whether tx is complete,i.e. data has been sent out.
__STATIC_INLINE uint8_t UART_IsTxBuffEmpty (UART_Type *pUART)
check whether Tx buffer is empty
__STATIC_INLINE uint8_t UART_IsRxBuffFull (UART_Type *pUART)
check whether Rx buffer is full, i.e. receive a character
Detailed Description
This section specifies the exact usage for each API function and macro.
Function Documentation
void UART_Init (UART_Type * pUART, UART_ConfigType * pConfig)
Parameters
[in] pUART base of UART port
[in] pConfig pointer to UART configuration structure
Returns
none
@ Pass/ Fail criteria: none
References UART_ConfigType::u32Baudrate, and UART_ConfigType::u32SysClkHz.
uint8_t UART_GetChar (UART_Type * pUART)
Parameters
[in] pUART base of UART port
Returns
unsigned char
void UART_PutChar (UART_Type * pUART, uint8_t u8Char)
Parameters
[in] pUART base of UART port
[in] u8Char char to send
Returns
none
void UART_SetBaudrate (UART_Type * pUART, UART_ConfigBaudrateType * pConfig)
Parameters
[in] pUART base of UART port
[in] pConfig baudrate config parameters
Returns
none
@ Pass/ Fail criteria:
References UART_ConfigBaudrateType::u32Baudrate, and UART_ConfigBaudrateType::u32SysClkHz.
void UART_EnableInterrupt (UART_Type * pUART, UART_InterruptType InterruptType)
Parameters
[in] pUART base of UART port
[in] InterruptType interrupt type
Returns
none
@ Pass/ Fail criteria:
References UART_FramingErrorInt, UART_IdleLineInt, UART_NoiseErrorInt, UART_ParityErrorInt, UART_RxBuffFullInt, UART_RxOverrunInt, UART_TxBuffEmptyInt, and UART_TxCompleteInt.
void UART_DisableInterrupt (UART_Type * pUART, UART_InterruptType InterruptType)
Parameters
[in] pUART base of UART port
[in] InterruptType interrupt type
Returns
none
@ Pass/ Fail criteria:
References UART_FramingErrorInt, UART_IdleLineInt, UART_NoiseErrorInt, UART_ParityErrorInt, UART_RxBuffFullInt, UART_RxOverrunInt, UART_TxBuffEmptyInt, and UART_TxCompleteInt.
uint16_t UART_GetFlags (UART_Type * pUART)
Parameters
[in] pUART base of UART port
Returns
16-bit flags
@ Pass/ Fail criteria:
uint8_t UART_CheckFlag (UART_Type * pUART, UART_FlagType FlagType)
Parameters
[in] pUART base of UART port
[in] FlagType flag type
Returns
1, flag is set 0, flag is clear
@ Pass/ Fail criteria: none
References UART_GetFlags().
void UART_SendWait (UART_Type * pUART, uint8_t * pSendBuff, uint32_t u32Length)
Parameters
[in] pUART base of UART port
[in] pSendBuff pointer of charecters to send
[in] u32Length number of charecters
Returns
none
@ Pass/ Fail criteria:
References UART_IsTxBuffEmpty(), UART_WriteDataReg(), and WDOG_Feed().
void UART_ReceiveWait (UART_Type * pUART, uint8_t * pReceiveBuff, uint32_t u32Length)
Parameters
[in] pUART base of UART port
[in] pReceiveBuff pointer of charecters to receive
[in] u32Length number of charecters
Returns
none
@ Pass/ Fail criteria:
References UART_IsRxBuffFull(), UART_ReadDataReg(), and WDOG_Feed().
void UART_WaitTxComplete (UART_Type * pUART)
Parameters
[in] pUART base of UART port
Returns
none
@ Pass/ Fail criteria: none
References UART_IsTxComplete().
void UART_SetCallback (UART_CallbackType pfnCallback)
Parameters
[in] pUART pointer to an UART register base
[in] pfnCallback callback routine
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t UART_ReadDataReg (UART_Type * pUART)
Parameters
[in] pUART base of UART port
Returns
unsign char received char
__STATIC_INLINE void UART_WriteDataReg (UART_Type * pUART, uint8_t u8Char)
Parameters
[in] pUART base of UART port
[in] u8Char char to send
Returns
none
__STATIC_INLINE uint8_t UART_CharPresent (UART_Type * pUART)
Parameters
[in] pUART base of UART port
Returns
0, No character received; no-zero, Character has been received
@ Pass/ Fail criteria:
__STATIC_INLINE void UART_EnableTx (UART_Type * pUART)
Parameters
[in] pUART base of UART port
Returns
none
__STATIC_INLINE void UART_DisableTx (UART_Type * pUART)
Parameters
[in] pUART base of UART port
Returns
none
__STATIC_INLINE void UART_EnableRx (UART_Type * pUART)
Parameters
[in] pUART base of UART port
Returns
none
__STATIC_INLINE void UART_DisableRx (UART_Type * pUART)
Parameters
[in] pUART base of UART port
Returns
none
__STATIC_INLINE void UART_EnableLoopback (UART_Type * pUART)
Parameters
[in] pUART base of UART port
Returns
none
__STATIC_INLINE void UART_EnableSingleWire (UART_Type * pUART)
Parameters
[in] pUART base of UART port
Returns
none
__STATIC_INLINE void UART_Set8BitMode (UART_Type * pUART)
Parameters
[in] pUART base of UART port
Returns
none
__STATIC_INLINE void UART_Set9BitMode (UART_Type * pUART)
Parameters
[in] pUART base of UART port
Returns
none
__STATIC_INLINE void UART_EnableTxBuffEmptyInt (UART_Type * pUART)
Parameters
[in] pUART base of UART port
Returns
none
@ Pass/ Fail criteria:
__STATIC_INLINE void UART_EnableTxCompleteInt (UART_Type * pUART)
Parameters
[in] pUART base of UART port
Returns
none
@ Pass/ Fail criteria:
__STATIC_INLINE void UART_EnableRxBuffFullInt (UART_Type * pUART)
Parameters
[in] pUART base of UART port
Returns
none
@ Pass/ Fail criteria:
__STATIC_INLINE void UART_DisableTxBuffEmptyInt (UART_Type * pUART)
Parameters
[in] pUART base of UART port
Returns
none
@ Pass/ Fail criteria:
__STATIC_INLINE void UART_DisableTxCompleteInt (UART_Type * pUART)
Parameters
[in] pUART base of UART port
Returns
none
@ Pass/ Fail criteria:
__STATIC_INLINE void UART_DisableRxBuffFullInt (UART_Type * pUART)
Parameters
[in] pUART base of UART port
Returns
none
@ Pass/ Fail criteria:
__STATIC_INLINE void UART_PutBreak (UART_Type * pUART)
Parameters
[in] pUART base of UART port
Returns
none
@ Pass/ Fail criteria:
__STATIC_INLINE uint8_t UART_IsTxComplete (UART_Type * pUART)
Parameters
[in] pUART base of UART port
Returns
1, Tx complete flag is set 0, Tx complete flag is clear
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t UART_IsTxBuffEmpty (UART_Type * pUART)
Parameters
[in] pUART base of UART port
Returns
1, Tx buffer is empty 0, Tx buffer is not empty
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t UART_IsRxBuffFull (UART_Type * pUART)
Parameters
[in] pUART base of UART port
Returns
1, Rx buffer is full 0, Rx buffer is not full
@ Pass/ Fail criteria: none