Kinetis E Peripheral Drivers: I2C API Specification
I2C API Specification
I2C Driver
Functions
void I2C_Init (I2C_Type *pI2Cx, I2C_ConfigPtr pI2CConfig)
Initialize I2C module.
uint8_t I2C_Start (I2C_Type *pI2Cx)
send out start signals.
uint8_t I2C_Stop (I2C_Type *pI2Cx)
send out stop signals.
uint8_t I2C_RepeatStart (I2C_Type *pI2Cx)
send out repeat start signals.
void I2C_SetSlaveAddress (I2C_Type *pI2Cx, uint16_t u16SlaveAddress)
set slave address.
void I2C_IntDisable (I2C_Type *pI2Cx)
disable IICIF interrupt.
void I2C_IntEnable (I2C_Type *pI2Cx)
enable IICIF interrupt.
void I2C_SetSCLLowTimeout (I2C_Type *pI2Cx, uint16_t u16Timeout)
SCL low timeout value that determines the timeout period of SCL low.
void I2C_Deinit (I2C_Type *pI2Cx)
deinit I2C module.
uint8_t I2C_WriteOneByte (I2C_Type *pI2Cx, uint8_t u8WrBuff)
write a byte to I2C module.
uint8_t I2C_ReadOneByte (I2C_Type *pI2Cx, uint8_t *pRdBuff, uint8_t u8Ack)
read a byte from slave I2C.
uint8_t I2C_MasterSendWait (I2C_Type *pI2Cx, uint16_t u16SlaveAddress, uint8_t *pWrBuff, uint32_t u32Length)
send data to I2C, and wait to complete transfering.
uint8_t I2C_MasterReadWait (I2C_Type *pI2Cx, uint16_t u16SlaveAddress, uint8_t *pRdBuff, uint32_t u32Length)
read data from I2C,and wait to complete transferring.
void I2C1_SetCallBack (I2C_CallbackType pCallBack)
set call back function for I2C1 module.
void I2C0_SetCallBack (I2C_CallbackType pCallBack)
set call back function for I2C0 module.
__STATIC_INLINE void I2C_TxEnable (I2C_Type *pI2Cx)
enable I2C to transmit data.
__STATIC_INLINE void I2C_RxEnable (I2C_Type *pI2Cx)
enable I2C to receive data.
__STATIC_INLINE void I2C_SetBaudRate (I2C_Type *pI2Cx, uint32_t u32Bps)
set IIC band rate.
__STATIC_INLINE void I2C_GeneralCallEnable (I2C_Type *pI2Cx)
enable general call.
__STATIC_INLINE void I2C_SMBusAlertEnable (I2C_Type *pI2Cx)
SMBus Alert Response Address Enable.
__STATIC_INLINE void I2C_RangeAddressEnable (I2C_Type *pI2Cx)
Range Address Matching Enable.
__STATIC_INLINE void I2C_SHTF2IntEnable (I2C_Type *pI2Cx)
SHTF2 Interrupt Enable.
__STATIC_INLINE void I2C_TimeoutCounterClockSelect (I2C_Type *pI2Cx, uint8_t u8Clock)
Timeout Counter Clock Select.
__STATIC_INLINE uint8_t I2C_GetStatus (I2C_Type *pI2Cx)
get I2C status.
__STATIC_INLINE void I2C_ClearStatus (I2C_Type *pI2Cx, uint8_t u8ClearFlag)
clear specified status.
__STATIC_INLINE void I2C_WriteDataReg (I2C_Type *pI2Cx, uint8_t u8DataBuff)
write data to data register.
__STATIC_INLINE uint8_t I2C_ReadDataReg (I2C_Type *pI2Cx)
read data from data register.
__STATIC_INLINE uint8_t I2C_IsTxMode (I2C_Type *pI2Cx)
check if is Tx mode.
__STATIC_INLINE uint8_t I2C_IsBusy (I2C_Type *pI2Cx)
check I2C if busy.
__STATIC_INLINE uint8_t I2C_IsReceivedAck (I2C_Type *pI2Cx)
check I2C receive ack or nack.
__STATIC_INLINE uint8_t I2C_IsMasterMode (I2C_Type *pI2Cx)
check I2C if is master mode.
__STATIC_INLINE uint8_t I2C_IsSMB_SLTF (I2C_Type *pI2Cx)
check SCL Low Timeout Flag.
__STATIC_INLINE uint8_t I2C_IsSMB_SHTF2 (I2C_Type *pI2Cx)
check SCL High Timeout Flag is set or clear.
__STATIC_INLINE void I2C_ClearSLTF (I2C_Type *pI2Cx)
clear SLTF flag.
__STATIC_INLINE void I2C_ClearSHTF2 (I2C_Type *pI2Cx)
clear SHTF2 flag.
__STATIC_INLINE void I2C_SendAck (I2C_Type *pI2Cx)
send out ACK.
__STATIC_INLINE void I2C_SendNack (I2C_Type *pI2Cx)
send out NACK.
__STATIC_INLINE void I2C_SecondAddressEnable (I2C_Type *pI2Cx)
Second I2C Address Enable.
Detailed Description
This section specifies the exact usage for each API function and macro.
Function Documentation
void I2C_Init (I2C_Type * pI2Cx, I2C_ConfigPtr pI2CConfig)
Parameters
[in] pI2Cx point to I2C module type.
[in] pI2CConfig point to I2C configure structure.
Returns
none
@ Pass/ Fail criteria: none
References I2C_SettingType::bAddressExt, I2C_SettingType::bFackEn, I2C_SettingType::bGCAEn, I2C_SettingType::bI2CEn, I2C_SettingType::bIntEn, I2C_SettingType::bRangeAddEn, I2C_SettingType::bSecondAddressEn, I2C_SettingType::bSHTF2IntEn, I2C_SettingType::bSMB_AlertEn, I2C_SettingType::bWakeUpEn, I2C_SetBaudRate(), I2C_SetSCLLowTimeout(), I2C_SetSlaveAddress(), I2C_ConfigType::u16F, I2C_ConfigType::u16Filt, I2C_ConfigType::u16OwnA1, I2C_ConfigType::u16RangeA, and I2C_ConfigType::u16Slt.
uint8_t I2C_Start (I2C_Type * pI2Cx)
Parameters
[in] pI2Cx point to I2C module type.
Returns
error status
@ Pass/ Fail criteria: none
References I2C_ERROR_START_NO_BUSY_FLAG, I2C_IsBusy(), and I2C_TxEnable().
uint8_t I2C_Stop (I2C_Type * pI2Cx)
Parameters
[in] pI2Cx point to I2C module type.
Returns
error status
@ Pass/ Fail criteria: none
References I2C_ERROR_STOP_BUSY_FLAG, and I2C_IsBusy().
uint8_t I2C_RepeatStart (I2C_Type * pI2Cx)
Parameters
[in] pI2Cx point to I2C module type.
Returns
error status.
@ Pass/ Fail criteria: none
References I2C_ERROR_START_NO_BUSY_FLAG, and I2C_IsBusy().
void I2C_SetSlaveAddress (I2C_Type * pI2Cx, uint16_t u16SlaveAddress)
Parameters
[in] pI2Cx point to I2C module type.
Returns
none
@ Pass/ Fail criteria: none
void I2C_IntDisable (I2C_Type * pI2Cx)
Parameters
[in] pI2Cx point to I2C module type.
Returns
none.
@ Pass/ Fail criteria: none
void I2C_IntEnable (I2C_Type * pI2Cx)
Parameters
[in] pI2Cx point to I2C module type.
Returns
none.
@ Pass/ Fail criteria: none.
void I2C_SetSCLLowTimeout (I2C_Type * pI2Cx, uint16_t u16Timeout)
Parameters
[in] pI2Cx point to I2C module type.
Returns
none.
@ Pass/ Fail criteria: none.
void I2C_Deinit (I2C_Type * pI2Cx)
Parameters
[in] pI2Cx point to I2C module type.
Returns
none
@ Pass/ Fail criteria: none
uint8_t I2C_WriteOneByte (I2C_Type * pI2Cx, uint8_t u8WrBuff)
Parameters
[in] pI2Cx point to I2C module type.
[in] u8WrBuff data buffer for writing.
Returns
error status
@ Pass/ Fail criteria: none
References I2C_ClearStatus(), I2C_ERROR_NO_GET_ACK, I2C_ERROR_NO_WAIT_IICIF_FLAG, I2C_ERROR_NO_WAIT_TCF_FLAG, I2C_GetStatus(), I2C_TxEnable(), and I2C_WriteDataReg().
uint8_t I2C_ReadOneByte (I2C_Type * pI2Cx, uint8_t * pRdBuff, uint8_t u8Ack)
Parameters
[in] pI2Cx point to I2C module type.
[out] pRdBuff point to the data read from slave I2C.
[out] u8Ack send out ack or nack.
Returns
error status
@ Pass/ Fail criteria: none
References I2C_ClearStatus(), I2C_ERROR_NO_WAIT_IICIF_FLAG, I2C_ERROR_NO_WAIT_TCF_FLAG, I2C_GetStatus(), I2C_ReadDataReg(), I2C_RxEnable(), I2C_SendAck(), and I2C_SendNack().
uint8_t I2C_MasterSendWait (I2C_Type * pI2Cx, uint16_t u16SlaveAddress, uint8_t * pWrBuff, uint32_t u32Length)
Parameters
[in] pI2Cx point to I2C module type.
[in] u16SlaveAddress slave address.
[in] pWrBuff point the first address of transfering data buffer.
[in] the length of transfering data.
Returns
error status
@ Pass/ Fail criteria: none
References I2C_ERROR_NULL, I2C_Start(), I2C_Stop(), I2C_WRITE, and I2C_WriteOneByte().
uint8_t I2C_MasterReadWait (I2C_Type * pI2Cx, uint16_t u16SlaveAddress, uint8_t * pRdBuff, uint32_t u32Length)
Parameters
[in] pI2Cx point to I2C module type.
[in] u16SlaveAddress slave address.
[in] pRdBuff point the first address of reading data buffer.
[in] the length of transfering data.
Returns
error status
@ Pass/ Fail criteria: none
References I2C_ERROR_NULL, I2C_READ, I2C_ReadOneByte(), I2C_Start(), I2C_Stop(), and I2C_WriteOneByte().
void I2C1_SetCallBack (I2C_CallbackType pCallBack)
Parameters
[in] pCallBack point to address of I2C1 call back function.
Returns
none.
@ Pass/ Fail criteria: none.
void I2C0_SetCallBack (I2C_CallbackType pCallBack)
Parameters
[in] pCallBack point to address of I2C0 call back function.
Returns
none.
@ Pass/ Fail criteria: none.
void I2C_TxEnable (I2C_Type * pI2Cx)
Parameters
[in] pI2Cx point to I2C module type.
Returns
none
@ Pass/ Fail criteria: none
void I2C_RxEnable (I2C_Type * pI2Cx)
Parameters
[in] pI2Cx point to I2C module type.
Returns
none.
@ Pass/ Fail criteria: none.
void I2C_SetBaudRate (I2C_Type * pI2Cx, uint32_t u32Bps)
Parameters
[in] pI2Cx point to I2C module type.
Returns
none
@ Pass/ Fail criteria: none
void I2C_GeneralCallEnable (I2C_Type * pI2Cx)
Parameters
[in] pI2Cx point to I2C module type.
Returns
none.
@ Pass/ Fail criteria: none.
void I2C_SMBusAlertEnable (I2C_Type * pI2Cx)
Parameters
[in] pI2Cx point to I2C module type.
Returns
none
@ Pass/ Fail criteria: none
void I2C_RangeAddressEnable (I2C_Type * pI2Cx)
Parameters
[in] pI2Cx point to I2C module type.
Returns
none
@ Pass/ Fail criteria: none
void I2C_SHTF2IntEnable (I2C_Type * pI2Cx)
Parameters
[in] pI2Cx point to I2C module type.
Returns
none
@ Pass/ Fail criteria: none
void I2C_TimeoutCounterClockSelect (I2C_Type * pI2Cx, uint8_t u8Clock)
Parameters
[in] pI2Cx point to I2C module type.
Returns
none
@ Pass/ Fail criteria: none
uint8_t I2C_GetStatus (I2C_Type * pI2Cx)
Parameters
[in] pI2Cx point to I2C module type.
Returns
I2C status
@ Pass/ Fail criteria: none
void I2C_ClearStatus (I2C_Type * pI2Cx, uint8_t u8ClearFlag)
Parameters
[in] pI2Cx point to I2C module type.
Returns
none
@ Pass/ Fail criteria: none
void I2C_WriteDataReg (I2C_Type * pI2Cx, uint8_t u8DataBuff)
Parameters
[in] pI2Cx point to I2C module type.
Returns
none
@ Pass/ Fail criteria: none
uint8_t I2C_ReadDataReg (I2C_Type * pI2Cx)
Parameters
[in] pI2Cx point to I2C module type.
Returns
I2C data register value
@ Pass/ Fail criteria: none
uint8_t I2C_IsTxMode (I2C_Type * pI2Cx)
Parameters
[in] pI2Cx point to I2C module type.
Returns
result TRUE or FALSE
@ Pass/ Fail criteria: none
uint8_t I2C_IsBusy (I2C_Type * pI2Cx)
Parameters
[in] pI2Cx point to I2C module type.
Returns
result TRUE or FALSE
@ Pass/ Fail criteria: none
uint8_t I2C_IsReceivedAck (I2C_Type * pI2Cx)
Parameters
[in] pI2Cx point to I2C module type.
Returns
result TRUE or FALSE
@ Pass/ Fail criteria: none.
uint8_t I2C_IsMasterMode (I2C_Type * pI2Cx)
Parameters
[in] pI2Cx point to I2C module type.
Returns
result TRUE or FALSE.
@ Pass/ Fail criteria: none.
uint8_t I2C_IsSMB_SLTF (I2C_Type * pI2Cx)
Parameters
[in] pI2Cx point to I2C module type.
Returns
result TRUE or FALSE.
@ Pass/ Fail criteria: none
uint8_t I2C_IsSMB_SHTF2 (I2C_Type * pI2Cx)
Parameters
[in] pI2Cx point to I2C module type.
Returns
result TRUE or FALSE.
@ Pass/ Fail criteria: none
void I2C_ClearSLTF (I2C_Type * pI2Cx)
Parameters
[in] pI2Cx point to I2C module type.
Returns
none.
@ Pass/ Fail criteria: none.
void I2C_ClearSHTF2 (I2C_Type * pI2Cx)
Parameters
[in] pI2Cx point to I2C module type.
Returns
none
@ Pass/ Fail criteria: none
void I2C_SendAck (I2C_Type * pI2Cx)
Parameters
[in] pI2Cx point to I2C module type.
Returns
none.
@ Pass/ Fail criteria: none.
void I2C_SendNack (I2C_Type * pI2Cx)
Parameters
[in] pI2Cx point to I2C module type.
Returns
none.
@ Pass/ Fail criteria: none.
void I2C_SecondAddressEnable (I2C_Type * pI2Cx)
Parameters
[in] pI2Cx point to I2C module type.
Returns
none.
@ Pass/ Fail criteria: none.