Kinetis E Peripheral Drivers: NVM API Specification
NVM API Specification
NVM Driver
Functions
uint16_t FLASH_Init (uint32_t u32BusClock)
initialize flash driver.
uint16_t FLASH_Program (uint32_t u32NVMTargetAddress, uint8_t *pData, uint16_t u16SizeBytes)
program flash routine.
uint16_t FLASH_Program1LongWord (uint32_t u32NVMTargetAddress, uint32_t u32DwData)
program flash routine, program 1 long word to flash.
uint16_t FLASH_Program2LongWords (uint32_t u32NVMTargetAddress, uint32_t u32DwData0, uint32_t u32DwData1)
program flash routine, program 2long word to flash.
uint16_t FLASH_EraseSector (uint32_t u32NVMTargetAddress)
erase flash sector, each flash sector is of 512 bytes long.
uint16_t FLASH_Unsecure (void)
unsecure device with unsecure command.
uint16_t FLASH_EraseBlock (uint32_t u32NVMTargetAddress, uint8_t bIsEEPROM)
erase flash/EEPROM block.
uint16_t FLASH_EraseVerifyBlock (uint32_t u32NVMTargetAddress, uint8_t bIsEEPROM)
erase verify flash/EEPROM block.
uint16_t FLASH_EraseVerifySection (uint32_t u32NVMTargetAddress, uint16_t u16LongWordCount)
erase verify flash section.
uint16_t FLASH_EraseVerifyAll (void)
erase verify all flash and EEPROM blocks.
uint16_t FLASH_EraseAll (void)
erase all flash and EEPROM blocks.
uint16_t FLASH_ProgramOnce (uint8_t u8PhraseIndex, uint8_t *pData8Bytes)
program once command, write data buff to IFR.
uint16_t FLASH_ReadOnce (uint8_t u8PhraseIndex, uint8_t *pData8Bytes)
read data from IFR address.
uint16_t FLASH_EraseBlock_NoWait (uint32_t u32NVMTargetAddress, uint8_t bIsEEPROM)
erase flash/Flash block without wait.
uint16_t FLASH_VerifyBackdoorKey (uint8_t *pKey)
verify backdoor key. NOTE: this routine must be running from RAM or EEPROM.
uint16_t FLASH_SetUserMarginLevel (uint32_t u32NVMTargetAddress, uint16_t u16MarginLevel, uint8_t bIsEEPROM)
set user margin level.
uint16_t FLASH_CheckErrStatus (void)
check flash error status.
void FLASH_LaunchCMD (uint8_t bWaitComplete)
launch NVM command. if bWaitComplete is true, then wait till command is completed. It should be placed in RAM for some commands like verify backdoor key if enabling flash controller bit is cleared. Otherwise, it can be executed in flash.
__STATIC_INLINE void FLASH_IntEnable (void)
Command Complete Interrupt Enable.
__STATIC_INLINE void FLASH_IntDisable (void)
Command Complete Interrupt Disable.
Detailed Description
This section specifies the exact usage for each API function and macro.
Function Documentation
uint16_t FLASH_Init (uint32_t u32BusClock)
Parameters
[in] u32BusClock current bus clock.
Returns
flash error status.
@ Pass/ Fail criteria: none.
References FLASH_ERR_INIT_CCIF, FLASH_ERR_INIT_FDIV, and FLASH_ERR_SUCCESS.
uint16_t FLASH_Program (uint32_t u32NVMTargetAddress, uint8_t * pData, uint16_t u16SizeBytes)
Parameters
[in] u32NVMTargetAddress programed flash address.
[in] pData programming data pointer.
[in] u16SizeBytes programming data length.
Returns
flash error status.
@ Pass/ Fail criteria: none.
References FLASH_ERR_INVALID_PARAM, FLASH_ERR_SUCCESS, FLASH_Program1LongWord(), and FLASH_Program2LongWords().
uint16_t FLASH_Program1LongWord (uint32_t u32NVMTargetAddress, uint32_t u32DwData)
Parameters
[in] u32NVMTargetAddress programed flash address.
[in] u32DwData programming data.
Returns
flash error status.
@ Pass/ Fail criteria: none.
References FLASH_CMD_PROGRAM, FLASH_ERR_ACCESS, FLASH_ERR_INVALID_PARAM, FLASH_ERR_MGSTAT0, FLASH_ERR_MGSTAT1, FLASH_ERR_PROTECTION, FLASH_ERR_SUCCESS, FLASH_LaunchCMD(), FTMRH_FSTAT_MGSTAT0_MASK, and FTMRH_FSTAT_MGSTAT1_MASK.
uint16_t FLASH_Program2LongWords (uint32_t u32NVMTargetAddress, uint32_t u32DwData0, uint32_t u32DwData1)
Parameters
[in] u32NVMTargetAddress programed flash address.
[in] u32DwData0 programming data0.
[in] u32DwData1 programming data1.
Returns
flash error status.
@ Pass/ Fail criteria: none
References FLASH_CMD_PROGRAM, FLASH_ERR_ACCESS, FLASH_ERR_INVALID_PARAM, FLASH_ERR_MGSTAT0, FLASH_ERR_MGSTAT1, FLASH_ERR_PROTECTION, FLASH_ERR_SUCCESS, FLASH_LaunchCMD(), FTMRH_FSTAT_MGSTAT0_MASK, and FTMRH_FSTAT_MGSTAT1_MASK.
uint16_t FLASH_EraseSector (uint32_t u32NVMTargetAddress)
Parameters
[in] u32NVMTargetAddress erase sector address.
Returns
error status.
@ Pass/ Fail criteria: none.
References EEPROM_ERR_DOUBLE_BIT_FAULT, EEPROM_ERR_SINGLE_BIT_FAULT, FLASH_CMD_ERASE_SECTOR, FLASH_ERR_ACCESS, FLASH_ERR_INVALID_PARAM, FLASH_ERR_MGSTAT0, FLASH_ERR_MGSTAT1, FLASH_ERR_PROTECTION, FLASH_ERR_SUCCESS, FLASH_LaunchCMD(), FTMRH_FSTAT_MGSTAT0_MASK, and FTMRH_FSTAT_MGSTAT1_MASK.
uint16_t FLASH_Unsecure (void)
Parameters
none.
Returns
error status.
@ Pass/ Fail criteria: none.
References EEPROM_ERR_DOUBLE_BIT_FAULT, EEPROM_ERR_SINGLE_BIT_FAULT, FLASH_ERR_ACCESS, FLASH_ERR_MGSTAT0, FLASH_ERR_MGSTAT1, FLASH_ERR_PROTECTION, FLASH_ERR_SUCCESS, FLASH_LaunchCMD(), FTMRH_CMD_UNSECURE, FTMRH_FSTAT_MGSTAT0_MASK, and FTMRH_FSTAT_MGSTAT1_MASK.
uint16_t FLASH_EraseBlock (uint32_t u32NVMTargetAddress, uint8_t bIsEEPROM)
Parameters
[in] u32NVMTargetAddress,: target address in NVM.
[in] bIsEEPROM,: specify the target address is within EEPROM,1 if in EEPROM block, 0 if in FLASH block.
Returns
error status.
@ Pass/ Fail criteria: none.
References EEPROM_ERR_DOUBLE_BIT_FAULT, EEPROM_ERR_SINGLE_BIT_FAULT, FLASH_ERR_ACCESS, FLASH_ERR_MGSTAT0, FLASH_ERR_MGSTAT1, FLASH_ERR_PROTECTION, FLASH_ERR_SUCCESS, FLASH_LaunchCMD(), FTMRH_CMD_ERASE_BLOCK, FTMRH_FSTAT_MGSTAT0_MASK, and FTMRH_FSTAT_MGSTAT1_MASK.
uint16_t FLASH_EraseVerifyBlock (uint32_t u32NVMTargetAddress, uint8_t bIsEEPROM)
Parameters
[in] u32NVMTargetAddress,: target address in NVM.
[in] bIsEEPROM,: specify the target address is within EEPROM,1 if in EEPROM block, 0 if in FLASH block.
Returns
error status.
@ Pass/ Fail criteria: none.
References EEPROM_ERR_DOUBLE_BIT_FAULT, EEPROM_ERR_SINGLE_BIT_FAULT, FLASH_ERR_ACCESS, FLASH_ERR_MGSTAT0, FLASH_ERR_MGSTAT1, FLASH_ERR_SUCCESS, FLASH_LaunchCMD(), FTMRH_CMD_ERASE_VERIFY_BLOCK, FTMRH_FSTAT_MGSTAT0_MASK, and FTMRH_FSTAT_MGSTAT1_MASK.
uint16_t FLASH_EraseVerifySection (uint32_t u32NVMTargetAddress, uint16_t u16LongWordCount)
Parameters
[in] u32NVMTargetAddress,: target address in NVM, must be longword aligned.
[in] u16LongWordCount,: number of longwords to be verified.
Returns
error status.
@ Pass/ Fail criteria: none.
References EEPROM_ERR_DOUBLE_BIT_FAULT, EEPROM_ERR_SINGLE_BIT_FAULT, FLASH_CMD_ERASE_VERIFY_SECTION, FLASH_ERR_ACCESS, FLASH_ERR_INVALID_PARAM, FLASH_ERR_MGSTAT0, FLASH_ERR_MGSTAT1, FLASH_ERR_PROTECTION, FLASH_ERR_SUCCESS, FLASH_LaunchCMD(), FTMRH_FSTAT_MGSTAT0_MASK, and FTMRH_FSTAT_MGSTAT1_MASK.
uint16_t FLASH_EraseVerifyAll (void)
Parameters
none.
Returns
error status.
@ Pass/ Fail criteria: none.
References EEPROM_ERR_DOUBLE_BIT_FAULT, EEPROM_ERR_SINGLE_BIT_FAULT, FLASH_ERR_ACCESS, FLASH_ERR_MGSTAT0, FLASH_ERR_MGSTAT1, FLASH_ERR_PROTECTION, FLASH_ERR_SUCCESS, FLASH_LaunchCMD(), FTMRH_CMD_ERASE_VERIFY_ALL, FTMRH_FSTAT_MGSTAT0_MASK, and FTMRH_FSTAT_MGSTAT1_MASK.
uint16_t FLASH_EraseAll (void)
Parameters
none.
Returns
error status.
@ Pass/ Fail criteria: none.
References EEPROM_ERR_DOUBLE_BIT_FAULT, EEPROM_ERR_SINGLE_BIT_FAULT, FLASH_ERR_ACCESS, FLASH_ERR_MGSTAT0, FLASH_ERR_MGSTAT1, FLASH_ERR_PROTECTION, FLASH_ERR_SUCCESS, FLASH_LaunchCMD(), FTMRH_CMD_ERASE_ALL, FTMRH_FSTAT_MGSTAT0_MASK, and FTMRH_FSTAT_MGSTAT1_MASK.
uint16_t FLASH_ProgramOnce (uint8_t u8PhraseIndex, uint8_t * pData8Bytes)
Parameters
[in] u8PhraseIndex phrase index.
[in] pData8Bytes programming data pointer.
Returns
error status.
@ Pass/ Fail criteria: none.
References FLASH_CMD_PROGRAMONCE, FLASH_ERR_ACCESS, FLASH_ERR_INVALID_PARAM, FLASH_ERR_MGSTAT0, FLASH_ERR_MGSTAT1, FLASH_ERR_PROTECTION, FLASH_ERR_SUCCESS, FLASH_LaunchCMD(), FTMRH_FSTAT_MGSTAT0_MASK, and FTMRH_FSTAT_MGSTAT1_MASK.
uint16_t FLASH_ReadOnce (uint8_t u8PhraseIndex, uint8_t * pData8Bytes)
Parameters
[in] u8PhraseIndex phrase index.
[out] pData8Bytes read data pointer.
Returns
error status.
@ Pass/ Fail criteria: none.
References FLASH_CMD_READONCE, FLASH_ERR_ACCESS, FLASH_ERR_INVALID_PARAM, FLASH_ERR_MGSTAT0, FLASH_ERR_MGSTAT1, FLASH_ERR_PROTECTION, FLASH_ERR_SUCCESS, FLASH_LaunchCMD(), FTMRH_FSTAT_MGSTAT0_MASK, and FTMRH_FSTAT_MGSTAT1_MASK.
uint16_t FLASH_EraseBlock_NoWait (uint32_t u32NVMTargetAddress, uint8_t bIsEEPROM)
Parameters
[in] u32NVMTargetAddress,: target address in NVM.
[in] bIsEEPROM,: specify the target address is within EEPROM, 1 if in EEPROM block, 0 if in FLASH block.
Returns
error status.
@ Pass/ Fail criteria: none.
References FLASH_ERR_SUCCESS, and FTMRH_CMD_ERASE_BLOCK.
uint16_t FLASH_VerifyBackdoorKey (uint8_t * pKey)
Parameters
[in] u32NVMTargetAddress,: target address in NVM, must be longword aligned.
[in] pKey,: pointer to 8-byte key.
Returns
error status.
@ Pass/ Fail criteria: none
References EEPROM_ERR_DOUBLE_BIT_FAULT, EEPROM_ERR_SINGLE_BIT_FAULT, FLASH_CMD_BACKDOOR_ACCESS, FLASH_ERR_ACCESS, FLASH_ERR_MGSTAT0, FLASH_ERR_MGSTAT1, FLASH_ERR_SUCCESS, FLASH_LaunchCMD(), FTMRH_FSTAT_MGSTAT0_MASK, and FTMRH_FSTAT_MGSTAT1_MASK.
uint16_t FLASH_SetUserMarginLevel (uint32_t u32NVMTargetAddress, uint16_t u16MarginLevel, uint8_t bIsEEPROM)
Parameters
[in] u32NVMTargetAddress,: target address in NVM, must be longword aligned.
[in] u16MarginLevel,: user margin level.
[in] bIsEEPROM,: true if EEPROM address, false if flash address.
Returns
error status.
@ Pass/ Fail criteria: none.
References EEPROM_ERR_DOUBLE_BIT_FAULT, EEPROM_ERR_SINGLE_BIT_FAULT, FLASH_CMD_SET_USER_MARGIN_LEVEL, FLASH_ERR_ACCESS, FLASH_ERR_INVALID_PARAM, FLASH_ERR_MGSTAT0, FLASH_ERR_MGSTAT1, FLASH_ERR_SUCCESS, FLASH_LaunchCMD(), FTMRH_FSTAT_MGSTAT0_MASK, and FTMRH_FSTAT_MGSTAT1_MASK.
uint16_t FLASH_CheckErrStatus (void)
Parameters
none.
Returns
flash error status.
@ Pass/ Fail criteria: none.
References FLASH_ERR_ACCESS, FLASH_ERR_MGSTAT0, FLASH_ERR_MGSTAT1, FLASH_ERR_PROTECTION, FLASH_ERR_SUCCESS, FTMRH_FSTAT_MGSTAT0_MASK, and FTMRH_FSTAT_MGSTAT1_MASK.
void FLASH_LaunchCMD (uint8_t bWaitComplete)
Parameters
[in] bWaitComplete,: true if need wait till command completed before return.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void FLASH_IntEnable (void)
Parameters
none.
Returns
none.
@ Pass/ Fail criteria: none.
__STATIC_INLINE void FLASH_IntDisable (void)
Parameters
none.
Returns
none.
@ Pass/ Fail criteria: none.