Kinetis E Peripheral Drivers: ADC API Specification
ADC API Specification
ADC Driver
Functions
void ADC_Init (ADC_Type *pADC, ADC_ConfigTypePtr pADC_Config)
initialize ADC module.
void ADC_DeInit (ADC_Type *pADC)
disable ADC module.
unsigned int ADC_PollRead (ADC_Type *pADC, uint8_t u8Channel)
start a conversion and get conversion result
void ADC_SetCallBack (ADC_CallbackType pADC_CallBack)
install ADC call back function.
void ADC_SetChannel (ADC_Type *pADC, uint8_t u8Channel)
set ADC channel.
void ADC_VrefSelect (ADC_Type *pADC, uint8_t u8Vref)
Voltage Reference Selection.
void ADC_SelectClockDivide (ADC_Type *pADC, uint8_t u8Div)
select clock divide
void ADC_SetMode (ADC_Type *pADC, uint8_t u8Mode)
set ADC mode.
void ADC_SelectClock (ADC_Type *pADC, uint8_t u8Clock)
Input Clock Select.
void ADC_SetFifoLevel (ADC_Type *pADC, uint8_t u8FifoLevel)
FIFO Depth enables.
__STATIC_INLINE void ADC_IntEnable (ADC_Type *pADC)
enable ADC interrupt.
__STATIC_INLINE void ADC_IntDisable (ADC_Type *pADC)
disable ADC interrupt.
__STATIC_INLINE void ADC_ContinuousConversion (ADC_Type *pADC)
enable ADC continuous conversion.
__STATIC_INLINE void ADC_SingleConversion (ADC_Type *pADC)
enable ADC single conversion
__STATIC_INLINE void ADC_SetHardwareTrigger (ADC_Type *pADC)
set the ADC to hardware trigger.
__STATIC_INLINE void ADC_SetSoftwareTrigger (ADC_Type *pADC)
set the ADC to software trigger.
__STATIC_INLINE void ADC_CompareEnable (ADC_Type *pADC)
enable ADC compare function.
__STATIC_INLINE void ADC_CompareDisable (ADC_Type *pADC)
disable ADC compare function.
__STATIC_INLINE void ADC_CompareGreaterFunction (ADC_Type *pADC)
enable ADC compare greater function.
__STATIC_INLINE void ADC_CompareLessFunction (ADC_Type *pADC)
enable ADC compare less function.
__STATIC_INLINE void ADC_SetLowPower (ADC_Type *pADC)
set ADC to low power configuration.
__STATIC_INLINE void ADC_SetHighSpeed (ADC_Type *pADC)
set ADC to high speed configuration.
__STATIC_INLINE void ADC_SetLongSample (ADC_Type *pADC)
Long Sample Time Configuration.
__STATIC_INLINE void ADC_SetShortSample (ADC_Type *pADC)
Short Sample Time Configuration.
__STATIC_INLINE void ADC_FifoScanModeEnable (ADC_Type *pADC)
FIFO scan mode enable.
__STATIC_INLINE void ADC_FifoScanModeDisable (ADC_Type *pADC)
FIFO scan mode disable.
__STATIC_INLINE void ADC_CompareFifoOr (ADC_Type *pADC)
OR all of compare trigger.
__STATIC_INLINE void ADC_CompareFifoAnd (ADC_Type *pADC)
And all of compare trigger.
__STATIC_INLINE uint16_t ADC_ReadResultReg (ADC_Type *pADC)
read ADC result register.
__STATIC_INLINE void ADC_SetCompareValue (ADC_Type *pADC, uint16_t u16Compare)
set ADC compare value.
__STATIC_INLINE void ADC_PinControlEnable (ADC_Type *pADC, uint16_t u16PinNumber)
ADC pin control enable.
__STATIC_INLINE void ADC_PinControlDisable (ADC_Type *pADC, uint16_t u16PinNumber)
ADC pin control disable.
__STATIC_INLINE uint8_t ADC_IsConversionActiveFlag (ADC_Type *pADC)
check conversion active status
__STATIC_INLINE uint8_t ADC_IsCOCOFlag (ADC_Type *pADC)
check COCO flag
__STATIC_INLINE uint8_t ADC_IsFIFOEmptyFlag (ADC_Type *pADC)
check Result FIFO empty
__STATIC_INLINE uint8_t ADC_IsFIFOFullFlag (ADC_Type *pADC)
check Result FIFO full
__STATIC_INLINE void ADC_HardwareTriggerMultiple (ADC_Type *pADC)
Hardware Trigger Multiple Conversion Enable.
__STATIC_INLINE void ADC_HardwareTriggerSingle (ADC_Type *pADC)
Hardware Trigger Single Conversion.
__STATIC_INLINE void ADC_HardwareTriggerMaskEnable (ADC_Type *pADC)
Hardware Trigger Mask Enable.
__STATIC_INLINE void ADC_HardwareTriggerMaskDisable (ADC_Type *pADC)
Hardware Trigger Mask Disable.
__STATIC_INLINE void ADC_HardwareTriggerMaskAuto (ADC_Type *pADC)
Hardware Trigger Mask Mode Select Automatic Mode.
__STATIC_INLINE void ADC_HardwareTriggerMaskNonAuto (ADC_Type *pADC)
Hardware Trigger Mask Mode Select to be with HTRGMASKE.
Detailed Description
This section specifies the exact usage for each API function and macro.
Function Documentation
void ADC_Init (ADC_Type * pADC, ADC_ConfigTypePtr pADC_Config)
Parameters
[in] pADC point to ADC module type.
[in] pADC_Config point to ADC configuration structure.
Returns
none
@ Pass/ Fail criteria: none
References ADC_CompareEnable(), ADC_CompareFifoAnd(), ADC_CompareGreaterFunction(), ADC_ContinuousConversion(), ADC_FifoScanModeEnable(), ADC_HardwareTriggerMaskAuto(), ADC_HardwareTriggerMaskDisable(), ADC_HardwareTriggerMaskEnable(), ADC_HardwareTriggerMaskNonAuto(), ADC_HardwareTriggerMultiple(), ADC_HardwareTriggerSingle(), ADC_IntEnable(), ADC_SelectClock(), ADC_SelectClockDivide(), ADC_SetFifoLevel(), ADC_SetHardwareTrigger(), ADC_SetLongSample(), ADC_SetLowPower(), ADC_SetMode(), ADC_SettingType::bCompareAndEn, ADC_SettingType::bCompareEn, ADC_SettingType::bCompareGreaterEn, ADC_SettingType::bContinuousEn, ADC_SettingType::bFiFoScanModeEn, ADC_SettingType::bHardwareTriggerEn, ADC_SettingType::bHTRGMASKEn, ADC_SettingType::bHTRGMASKSEL, ADC_SettingType::bHTRGMEn, ADC_SettingType::bIntEn, ADC_SettingType::bLongSampleEn, ADC_SettingType::bLowPowerEn, ADC_ConfigType::sSetting, ADC_ConfigType::u16PinControl, ADC_ConfigType::u8ClockDiv, ADC_ConfigType::u8ClockSource, ADC_ConfigType::u8FiFoLevel, and ADC_ConfigType::u8Mode.
void ADC_DeInit (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
none.
@ Pass/ Fail criteria: none.
References ADC_CHANNEL_DISABLE, and ADC_SetChannel().
unsigned int ADC_PollRead (ADC_Type * pADC, uint8_t u8Channel)
Parameters
[in] pADC point to ADC module type.
[in] u8Channel adc channel to conversion.
Returns
ADC conversion result.
@ Pass/ Fail criteria: none
References ADC_IsCOCOFlag(), ADC_ReadResultReg(), and ADC_SetChannel().
void ADC_SetCallBack (ADC_CallbackType pADC_CallBack)
Parameters
[in] pADC_CallBack point to address of adc call back function.
Returns
none.
@ Pass/ Fail criteria: none.
void ADC_SetChannel (ADC_Type * pADC, uint8_t u8Channel)
Parameters
[in] pADC point to ADC module type.
[in] u8Channel adc channel to conversion.
Returns
none
@ Pass/ Fail criteria: none
void ADC_VrefSelect (ADC_Type * pADC, uint8_t u8Vref)
Parameters
[in] pADC point to ADC module type.
[in] u8Vref adc reference voltage selection.
Returns
none
@ Pass/ Fail criteria: none
void ADC_SelectClockDivide (ADC_Type * pADC, uint8_t u8Div)
Parameters
[in] pADC point to ADC module type.
[in] u8Div Clock Divide Select.
Returns
none
@ Pass/ Fail criteria: none
void ADC_SetMode (ADC_Type * pADC, uint8_t u8Mode)
Parameters
[in] pADC point to ADC module type.
[in] u8Mode Conversion Mode Selection.
Returns
none
@ Pass/ Fail criteria: none
void ADC_SelectClock (ADC_Type * pADC, uint8_t u8Clock)
Parameters
[in] pADC point to ADC module type.
[in] u8Clock Input Clock Select.
Returns
none
@ Pass/ Fail criteria: none
void ADC_SetFifoLevel (ADC_Type * pADC, uint8_t u8FifoLevel)
Parameters
[in] pADC point to ADC module type.
[in] u8FifoLevel set FIFO level.
Returns
none
@ Pass/ Fail criteria: none
void ADC_IntEnable (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
none
@ Pass/ Fail criteria: none
void ADC_IntDisable (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
none
@ Pass/ Fail criteria: none
void ADC_ContinuousConversion (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
none
@ Pass/ Fail criteria: none
void ADC_SingleConversion (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
none
@ Pass/ Fail criteria: none
void ADC_SetHardwareTrigger (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
none.
@ Pass/ Fail criteria: none.
void ADC_SetSoftwareTrigger (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
none
@ Pass/ Fail criteria: none
void ADC_CompareEnable (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
none
@ Pass/ Fail criteria: none
void ADC_CompareDisable (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
none
@ Pass/ Fail criteria: none
void ADC_CompareGreaterFunction (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
none
@ Pass/ Fail criteria: none
void ADC_CompareLessFunction (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
none
@ Pass/ Fail criteria: none
void ADC_SetLowPower (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
none
@ Pass/ Fail criteria: none
void ADC_SetHighSpeed (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
none
@ Pass/ Fail criteria: none
void ADC_SetLongSample (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
none
@ Pass/ Fail criteria: none
void ADC_SetShortSample (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
none
@ Pass/ Fail criteria: none
void ADC_FifoScanModeEnable (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
none.
@ Pass/ Fail criteria: none.
void ADC_FifoScanModeDisable (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
none
@ Pass/ Fail criteria: none
void ADC_CompareFifoOr (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
none
@ Pass/ Fail criteria: none
void ADC_CompareFifoAnd (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
none
@ Pass/ Fail criteria: none
uint16_t ADC_ReadResultReg (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
ADC result value.
@ Pass/ Fail criteria: none
void ADC_SetCompareValue (ADC_Type * pADC, uint16_t u16Compare)
Parameters
[in] pADC point to ADC module type.
[in] u16Compare compare value.
Returns
none
@ Pass/ Fail criteria: none
void ADC_PinControlEnable (ADC_Type * pADC, uint16_t u16PinNumber)
Parameters
[in] pADC point to ADC module type.
[in] u16PinNumber enable ADC function to specified pin number.
Returns
none
@ Pass/ Fail criteria: none
void ADC_PinControlDisable (ADC_Type * pADC, uint16_t u16PinNumber)
Parameters
[in] pADC point to ADC module type.
[in] u16PinNumber disable ADC function to specified pin number.
Returns
none
@ Pass/ Fail criteria: none
uint8_t ADC_IsConversionActiveFlag (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
TRUE or FALSE
@ Pass/ Fail criteria: none
uint8_t ADC_IsCOCOFlag (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
TRUE or FALSE
@ Pass/ Fail criteria: none
uint8_t ADC_IsFIFOEmptyFlag (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
TRUE or FALSE
@ Pass/ Fail criteria: none
uint8_t ADC_IsFIFOFullFlag (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
TRUE or FALSE
@ Pass/ Fail criteria: none
void ADC_HardwareTriggerMultiple (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
none
@ Pass/ Fail criteria: none
void ADC_HardwareTriggerSingle (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
none
@ Pass/ Fail criteria: none
void ADC_HardwareTriggerMaskEnable (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
none
@ Pass/ Fail criteria: none
void ADC_HardwareTriggerMaskDisable (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
none
@ Pass/ Fail criteria: none
void ADC_HardwareTriggerMaskAuto (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
none
@ Pass/ Fail criteria: none
void ADC_HardwareTriggerMaskNonAuto (ADC_Type * pADC)
Parameters
[in] pADC point to ADC module type.
Returns
none
@ Pass/ Fail criteria: none