Kinetis E Peripheral Drivers: Flextimer API Specification
Flextimer API Specification
Flextimer Driver
Functions
void FTM_ClockSet (FTM_Type *pFTM, uint8_t u8ClockSource, uint8_t u8ClockPrescale)
set the ftm moule clock source and prescale.
void FTM_PWMInit (FTM_Type *pFTM, uint8_t u8PWMModeSelect, uint8_t u8PWMEdgeSelect)
general configuration to FTM_No to high ture EPWM mode, clock soure is the system clock, MOD, CnV are the initial value.
void FTM_InputCaptureInit (FTM_Type *pFTM, uint8_t u8FTM_Channel, uint8_t u8CaptureMode)
general configuration to FTM_No to input capture mode, enable interrupt.
void FTM_DualEdgeCaptureInit (FTM_Type *pFTM, uint8_t u8ChannelPair, uint8_t u8CaptureMode, uint8_t u8Channel_N_Edge, uint8_t u8Channel_Np1_Edge)
general configuration to FTM_No to Dual Edge Capture mode to measure the width or the period of a pulse.
void FTM_OutputCompareInit (FTM_Type *pFTM, uint8_t u8FTM_Channel, uint8_t u8CompareMode)
general configuration to FTM_No to input capture mode.
void FTM_SoftwareSync (FTM_Type *pFTM)
general configuration to FTM2 to start software synchronization.
void FTM_HardwareSync (FTM_Type *pFTM, uint8_t u8TriggerN)
general configuration to FTM to enable hardware synchronization.
void FTM_HardwareSyncCombine (FTM_Type *pFTM, uint8_t u8TriggerMask)
general configuration to FTM to enable hardware synchronization, more then 1 trigger.
void FTM_GenerateTrig2 (FTM_Type *pFTM)
generate FTM2 hardware trigger 2,Note: please call FTM_HardwareSyncCombine first.
void FTM_PWMDeadtimeSet (FTM_Type *pFTM, uint8_t u8PrescalerValue, uint8_t u8DeadtimeValue)
general configuration to FTM_No to start software synchronization.
void FTM_OutputMaskSet (FTM_Type *pFTM, uint8_t u8FTM_Channel)
set output mask.
void FTM_SWOutputControlSet (FTM_Type *pFTM, uint8_t u8FTM_Channel, uint8_t u8ChannelValue)
general configuration to FTM_No to start software synchronization.
void FTM_PolaritySet (FTM_Type *pFTM, uint8_t u8FTM_Channel, uint8_t u8ActiveValue)
set PWM polarity.
void FTM_SetDebugModeBehavior (FTM_Type *pFTM, uint8_t u8DebugMode)
set FTM behavior in debug mode.
void FTM_SetTOFFrequency (FTM_Type *pFTM, uint8_t u8TOFNUM)
Selects the ratio between the number of counter overflows to the number of times the TOF bit is set.
void FTM_InvertChannel (FTM_Type *pFTM, uint8_t u8ChannelPair)
swap the output of CH(n) and CH(n+1).
void FTM_Init (FTM_Type *pFTM, FTM_ConfigType *pConfig)
configure the FTM as specified control parameters, CnSC and CnV not included.
void FTM_DeInit (FTM_Type *pFTM)
close the FTM moudle.
void FTM_ChannelInit (FTM_Type *pFTM, uint8_t u8FTM_Channel, FTM_ChParamsType *pTFTMCH_Params)
configure the FTM channels, CnSC and CnV are included.
void FTM_SetDutyCycleCombine (FTM_Type *pFTM, uint8_t u8FTM_Channel, uint8_t u8DutyCycle)
set the FTM channel value register per duty cycle and modulo for combine mode odd channel no must be provided and even channel value register is not changed.
void FTM_SyncConfigActivate (FTM_Type *pFTM, uint32_t u32ConfigValue)
configure the FTMx_SYNCONF register including SW and HW Sync selection.
void FTM_SyncConfigDeactivate (FTM_Type *pFTM, uint32_t u32ConfigValue)
configure the FTMx_SYNCONF register including SW and HW Sync selection.
void FTM_SetCallback (FTM_Type *pFTM, FTM_CallbackPtr pfnCallback)
This function sets the callback function.
__STATIC_INLINE void FTM_EnableOverflowInt (FTM_Type *pFTM)
enable the over flow interrupt.
__STATIC_INLINE void FTM_DisableOverflowInt (FTM_Type *pFTM)
disable the over flow interrupt.
__STATIC_INLINE void FTM_EnableChannelInt (FTM_Type *pFTM, uint8_t u8FTM_Channel)
enable the channel interrupt.
__STATIC_INLINE void FTM_DisableChannelInt (FTM_Type *pFTM, uint8_t u8FTM_Channel)
disable the channel interrupt.
__STATIC_INLINE uint8_t FTM_GetOverFlowFlag (FTM_Type *pFTM)
get the over flow flag.
__STATIC_INLINE void FTM_ClrOverFlowFlag (FTM_Type *pFTM)
clear the over flow flag.
__STATIC_INLINE uint8_t FTM_GetChannelFlag (FTM_Type *pFTM, uint8_t u8FTM_Channel)
get the channel flag.
__STATIC_INLINE void FTM_ClrChannelFlag (FTM_Type *pFTM, uint8_t u8FTM_Channel)
clear the channel flag.
__STATIC_INLINE void FTM_WriteProtectionEnable (FTM_Type *pFTM)
enable the write protection function.Write protected bits cannot be written.
__STATIC_INLINE void FTM_WriteProtectionDisable (FTM_Type *pFTM)
disable the write protection function.Write protected bits can be written.
__STATIC_INLINE void FTM_SetFTMEnhanced (FTM_Type *pFTM)
set FTMEN bit to enable FTM-specific register.
__STATIC_INLINE void FTM_SetFTMBasic (FTM_Type *pFTM)
clear FTMEN bit to disable FTM-specific registers, only TPM-compatible registers can be used.
__STATIC_INLINE void FTM_SetModValue (FTM_Type *pFTM, uint16_t u16ModValue)
set the ftm mod value.
__STATIC_INLINE void FTM_SetChannelValue (FTM_Type *pFTM, uint8_t u8FTM_Channel, uint16_t u16ChannelValue)
set the ftm channel value.
__STATIC_INLINE void FTM_SetCounterInitValue (FTM_Type *pFTM, uint16_t u16CounterValue)
set the ftm channel value.
__STATIC_INLINE void FTM_MaskChannels (FTM_Type *pFTM, uint16_t u16ChMask)
set the channel output mask value, FTM2 used only.
__STATIC_INLINE void FTM_UnMaskChannels (FTM_Type *pFTM, uint16_t u16ChMask)
clear the channel output mask value, FTM2 used only.
__STATIC_INLINE void FTM_SetChannelsPolarity (FTM_Type *pFTM, uint8_t u8ChsPolValue)
set FTM channels polarity.
__STATIC_INLINE uint8_t FTM_GetChannelsPolarity (FTM_Type *pFTM)
get FTM channels polarity.
__STATIC_INLINE void FTM_EnableEnhancedSYNCMode (FTM_Type *pFTM)
select the enhanced SYNC mode.
__STATIC_INLINE void FTM_DisableEnhancedSYNCMode (FTM_Type *pFTM)
select the legacy SYNC mode.
__STATIC_INLINE void FTM_SetExternalTrigger (FTM_Type *pFTM, uint8_t u8TirggerSource)
set the external trigger source.
__STATIC_INLINE uint8_t FTM_GetExternalTriggerFlag (FTM_Type *pFTM)
get the external trigger flag.
__STATIC_INLINE void FTM_SetLoadEnable (FTM_Type *pFTM)
set LDOK bit.
__STATIC_INLINE void FTM_SetLoadMatchChannel (FTM_Type *pFTM, uint8_t u8Matchchannel)
set the channel in the matching process.
__STATIC_INLINE void FTM_InputCaptureFilterClr (FTM_Type *pFTM, uint8_t u8FTM_Channel)
disable the channel input capture filter.
__STATIC_INLINE void FTM_InputCaptureFilterSet (FTM_Type *pFTM, uint8_t u8FTM_Channel, uint8_t u8FilterValue)
set the channel input capture filter value.
__STATIC_INLINE void FTM_FaultPinEnable (FTM_Type *pFTM, uint8_t u8FaultPin)
enable the fault input pin.
__STATIC_INLINE void FTM_FaultPinDisable (FTM_Type *pFTM, uint8_t u8FaultPin)
disable the fault input pin.
__STATIC_INLINE void FTM_FaultPinFilterEnable (FTM_Type *pFTM, uint8_t u8FaultPin)
enable the fault pin filter.
__STATIC_INLINE void FTM_FaultPinFilterDisable (FTM_Type *pFTM, uint8_t u8FaultPin)
disable the fault pin filter.
__STATIC_INLINE void FTM_FaultPinFilterCDisableAll (FTM_Type *pFTM)
disable all the fault pins filter together.
__STATIC_INLINE void FTM_FaultPinFilterSet (FTM_Type *pFTM, uint8_t u8FilterValue)
set the fault filter value. All channels share the same filter value.
__STATIC_INLINE uint8_t FTM_GetFaultDetectionLogicORFlag (FTM_Type *pFTM)
get the logic OR of all the fault detection flags
__STATIC_INLINE uint8_t FTM_GetFaultDetectionFlag (FTM_Type *pFTM, uint8_t u8FaultPin)
get the fault detection flag
__STATIC_INLINE uint8_t FTM_GetFaultInputsLogicORValue (FTM_Type *pFTM)
get the logic OR value of the fault inputs
Detailed Description
This section specifies the exact usage for each API function and macro.
inline functions
Function Documentation
void FTM_ClockSet (FTM_Type * pFTM, uint8_t u8ClockSource, uint8_t u8ClockPrescale)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] ClockSource ftm clock source.
[in] ClockPrescale prescale factor.
Returns
none.
@ Pass/ Fail criteria: none.
void FTM_PWMInit (FTM_Type * pFTM, uint8_t u8PWMModeSelect, uint8_t u8PWMEdgeSelect)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] PWMModeSelect select CPWM , EPWM or combine pwm mode.
[in] PWMEdgeSelect select high true or low true pulse.
Returns
none.
@ Pass/ Fail criteria: none.
References FTM_C0V_INIT, FTM_MOD_INIT, FTM_PWM_HIGHTRUEPULSE, FTM_PWM_LOWTRUEPULSE, FTM_PWMMODE_CENTERALLIGNED, and FTM_PWMMODE_COMBINE.
void FTM_InputCaptureInit (FTM_Type * pFTM, uint8_t u8FTM_Channel, uint8_t u8CaptureMode)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] Channel channel number to be configured.
[in] CaptureMode select capture edge: rising, falling or both.
Returns
none.
@ Pass/ Fail criteria: none.
References FTM_INPUTCAPTURE_BOTHEDGE, FTM_INPUTCAPTURE_FALLINGEDGE, and FTM_INPUTCAPTURE_RISINGEDGE.
void FTM_DualEdgeCaptureInit (FTM_Type * pFTM, uint8_t u8ChannelPair, uint8_t u8CaptureMode, uint8_t u8Channel_N_Edge, uint8_t u8Channel_Np1_Edge)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] ChannelPair ChannelPair number to be configured: 0, 2, 4.
[in] CaptureMode select capture edge: one shot and continuous mode.
[in] Channel_N_Edge channel N detect edge.
[in] Channel_Np1_Edge channel N+1 detect edge.
Returns
none.
@ Pass/ Fail criteria: none.
References FTM_INPUTCAPTURE_DUALEDGE_CONTINUOUS, and FTM_INPUTCAPTURE_DUALEDGE_ONESHOT.
void FTM_OutputCompareInit (FTM_Type * pFTM, uint8_t u8FTM_Channel, uint8_t u8CompareMode)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] Channel channel number to be configured.
[in] CompareMode select compare edge: toggle, set and clear.
Returns
none.
@ Pass/ Fail criteria: none.
References FTM_C0V_INIT, and FTM_MOD_INIT.
void FTM_SoftwareSync (FTM_Type * pFTM)
Parameters
[in] pFTM pointer to one of three FTM base register address.
Returns
none.
@ Pass/ Fail criteria: none.
void FTM_HardwareSync (FTM_Type * pFTM, uint8_t u8TriggerN)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] u8TriggerN select the hardware trigger source.
Returns
none.
@ Pass/ Fail criteria: none.
References FTM_SYNC_TRIGGER_TRIGGER0, FTM_SYNC_TRIGGER_TRIGGER1, and FTM_SYNC_TRIGGER_TRIGGER2.
void FTM_HardwareSyncCombine (FTM_Type * pFTM, uint8_t u8TriggerMask)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] u8TriggerMask select the hardware trigger source. combine TRIG0~TREG2.(x000xxxx~x111xxxx)
Returns
none.
@ Pass/ Fail criteria: none.
void FTM_GenerateTrig2 (FTM_Type * pFTM)
Parameters
[in] pFTM pointer to one of three FTM base register address.
Returns
none.
@ Pass/ Fail criteria: none.
void FTM_PWMDeadtimeSet (FTM_Type * pFTM, uint8_t u8PrescalerValue, uint8_t u8DeadtimeValue)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] PrescalerValue system clock divide value, 0 to 3.
[in] DeadtimeValue n count clock is inserted, 0 to 63.
Returns
none.
@ Pass/ Fail criteria: none.
void FTM_OutputMaskSet (FTM_Type * pFTM, uint8_t u8FTM_Channel)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] Channel pwm channel needed to be masked.
Returns
none.
@ Pass/ Fail criteria: none.
void FTM_SWOutputControlSet (FTM_Type * pFTM, uint8_t u8FTM_Channel, uint8_t u8ChannelValue)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] Channel pwm channel needed to be controlled by software.
[in] ChannelValue the value to be set, 0 or 1.
Returns
none.
@ Pass/ Fail criteria: none.
References FTM_SWOCTRL_HIGH, and FTM_SWOCTRL_LOW.
void FTM_PolaritySet (FTM_Type * pFTM, uint8_t u8FTM_Channel, uint8_t u8ActiveValue)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] Channel pwm channel needed to be controlled by software.
[in] ActiveValue the value to be set, 0 or 1.
Returns
none.
@ Pass/ Fail criteria: none.
References FTM_POLARITY_HIGHACTIVE, and FTM_POLARITY_LOWACTIVE.
void FTM_SetDebugModeBehavior (FTM_Type * pFTM, uint8_t u8DebugMode)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] u8DebugMode debug mode select from 00 to 11.
Returns
none.
@ Pass/ Fail criteria: none.
void FTM_SetTOFFrequency (FTM_Type * pFTM, uint8_t u8TOFNUM)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] u8TOFNUM TOF numbers before setting TOF bit, 0~31.
Returns
none.
@ Pass/ Fail criteria: none.
void FTM_InvertChannel (FTM_Type * pFTM, uint8_t u8ChannelPair)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] ChannelPair the pair to be swapped, 0,1,2.
Returns
none.
@ Pass/ Fail criteria: none.
void FTM_Init (FTM_Type * pFTM, FTM_ConfigType * pConfig)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] pConfig pointer to FTM general parameters.
Returns
none.
@ Pass/ Fail criteria: none.
References FTM_ConfigType::cnt, FTM_ConfigType::cntin, FTM_ConfigType::combine, FTM_ConfigType::conf, FTM_ConfigType::deadtime, FTM_ConfigType::exttrig, FTM_ConfigType::filter, FTM_ConfigType::fltctrl, FTM_ConfigType::fltpol, FTM_ConfigType::fms, FTM_ConfigType::mode, FTM_ConfigType::modulo, FTM_ConfigType::outinit, FTM_ConfigType::outmask, FTM_ConfigType::pol, FTM_ConfigType::pwmload, FTM_ConfigType::sc, FTM_ConfigType::swoctrl, FTM_ConfigType::sync, and FTM_ConfigType::synconf.
void FTM_DeInit (FTM_Type * pFTM)
Parameters
[in] pFTM pointer to one of three FTM base register address.
Returns
none.
@ Pass/ Fail criteria: none.
void FTM_ChannelInit (FTM_Type * pFTM, uint8_t u8FTM_Channel, FTM_ChParamsType * pTFTMCH_Params)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] FTM_Channel FTM channel number.
[in] pTFTMCH_Params pointer to FTM channel general parameters.
Returns
none.
@ Pass/ Fail criteria: none.
References FTM_ChParamsType::u16CnV, and FTM_ChParamsType::u8CnSC.
void FTM_SetDutyCycleCombine (FTM_Type * pFTM, uint8_t u8FTM_Channel, uint8_t u8DutyCycle)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] FTM_Channel odd channel no:1,3,5.
[in] dutyCycle duty cycle in percentage. e.g. 10, means 10%.
Returns
none.
@ Pass/ Fail criteria: none.
void FTM_SyncConfigActivate (FTM_Type * pFTM, uint32_t u32ConfigValue)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] u32ConfigValue FTMx_SYNCONF register config value.
Returns
none.
@ Pass/ Fail criteria: none.
void FTM_SyncConfigDeactivate (FTM_Type * pFTM, uint32_t u32ConfigValue)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] u32ConfigValue FTMx_SYNCONF register config value.
Returns
none.
@ Pass/ Fail criteria: none.
void FTM_SetCallback (FTM_Type * pFTM, FTM_CallbackPtr pfnCallback)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] pfnCallback functon address.
Returns
none.
@ Pass/ Fail criteria: none
void FTM_EnableOverflowInt (FTM_Type * pFTM)
Parameters
[in] pFTM pointer to one of three FTM base register address.
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_DisableOverflowInt.
void FTM_DisableOverflowInt (FTM_Type * pFTM)
Parameters
[in] pFTM pointer to one of three FTM base register address.
Returns
none.
@ Pass/ Fail criteria: none
See Also
FTM_EnableOverflowInt.
void FTM_EnableChannelInt (FTM_Type * pFTM, uint8_t u8FTM_Channel)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] u8FTM_Channel channel number.
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_DisableChannelInt.
void FTM_DisableChannelInt (FTM_Type * pFTM, uint8_t u8FTM_Channel)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] u8FTM_Channel channel number.
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_EnableChannelInt.
uint8_t FTM_GetOverFlowFlag (FTM_Type * pFTM)
Parameters
[in] pFTM pointer to one of three FTM base register address.
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_ClrOverFlowFlag.
void FTM_ClrOverFlowFlag (FTM_Type * pFTM)
Parameters
[in] pFTM pointer to one of three FTM base register address.
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_GetOverFlowFlag.
uint8_t FTM_GetChannelFlag (FTM_Type * pFTM, uint8_t u8FTM_Channel)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] u8FTM_Channel channel number.
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_ClrChannelFlag.
void FTM_ClrChannelFlag (FTM_Type * pFTM, uint8_t u8FTM_Channel)
Parameters
[in] pFTM pointer to one of three FTM base register address.
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_GetChannelFlag.
void FTM_WriteProtectionEnable (FTM_Type * pFTM)
Parameters
[in] pFTM pointer to one of three FTM base register address.
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_WriteProtectionDisable.
void FTM_WriteProtectionDisable (FTM_Type * pFTM)
Parameters
[in] pFTM pointer to one of three FTM base register address.
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_WriteProtectionDisable.
void FTM_SetFTMEnhanced (FTM_Type * pFTM)
Parameters
[in] pFTM pointer to one of three FTM base register address.
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_SetFTMBasic.
References FTM_WriteProtectionDisable(), and FTM_WriteProtectionEnable().
void FTM_SetFTMBasic (FTM_Type * pFTM)
Parameters
[in] pFTM pointer to one of three FTM base register address.
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_SetFTMEnhanced.
References FTM_WriteProtectionDisable(), and FTM_WriteProtectionEnable().
void FTM_SetModValue (FTM_Type * pFTM, uint16_t u16ModValue)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] u16ModValue the mod value required to set.
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_SetChannelValue.
void FTM_SetChannelValue (FTM_Type * pFTM, uint8_t u8FTM_Channel, uint16_t u16ChannelValue)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] u16ChannelValue the CnV value required to set.
[in] u8FTM_Channel ftm channel number.
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_SetModValue.
void FTM_SetCounterInitValue (FTM_Type * pFTM, uint16_t u16CounterValue)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] u16CounterValue the CNTIN value required to set.
Returns
none.
@ Pass/ Fail criteria: none
See Also
FTM_SetModValue.
void FTM_MaskChannels (FTM_Type * pFTM, uint16_t u16ChMask)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] u16ChMask the CNTIN value required to set.
Returns
none.
@ Pass/ Fail criteria: none
See Also
FTM_UnMaskChannels.
void FTM_UnMaskChannels (FTM_Type * pFTM, uint16_t u16ChMask)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] u16ChMask the CNTIN value required to set.
Returns
none.
@ Pass/ Fail criteria: none
See Also
FTM_MaskChannels.
void FTM_SetChannelsPolarity (FTM_Type * pFTM, uint8_t u8ChsPolValue)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] u8ChsPolValue the channels value need to be set.
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_GetChannelsPolarity.
uint8_t FTM_GetChannelsPolarity (FTM_Type * pFTM)
Parameters
[in] pFTM pointer to one of three FTM base register address.
Returns
uint8_t the channels polarity.
@ Pass/ Fail criteria: none.
See Also
FTM_SetChannelsPolarity.
void FTM_EnableEnhancedSYNCMode (FTM_Type * pFTM)
Parameters
[in] pFTM pointer to one of three FTM base register address.
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_DisableEnhancedSYNCMode.
void FTM_DisableEnhancedSYNCMode (FTM_Type * pFTM)
Parameters
[in] pFTM pointer to one of three FTM base register address.
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_EnableEnhancedSYNCMode.
__STATIC_INLINE void FTM_SetExternalTrigger (FTM_Type * pFTM, uint8_t u8TirggerSource)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] u8TirggerSource initial trigger or CHn(0~5)trigger
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_GetExternalTriggerFlag.
uint8_t FTM_GetExternalTriggerFlag (FTM_Type * pFTM)
Parameters
[in] pFTM pointer to one of three FTM base register address.
Returns
ex trigger flag.
@ Pass/ Fail criteria: none.
See Also
FTM_SetExternalTrigger.
void FTM_SetLoadEnable (FTM_Type * pFTM)
Parameters
[in] pFTM pointer to one of three FTM base register address.
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_SetLoadMatchChannel.
void FTM_SetLoadMatchChannel (FTM_Type * pFTM, uint8_t u8Matchchannel)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] u8Matchchannel the channel in the matching process.
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_SetLoadEnable.
void FTM_InputCaptureFilterClr (FTM_Type * pFTM, uint8_t u8FTM_Channel)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] u8FTM_Channel the channel number: 0~3.
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_InputCaptureFilterSet.
void FTM_InputCaptureFilterSet (FTM_Type * pFTM, uint8_t u8FTM_Channel, uint8_t u8FilterValue)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] u8FTM_Channel the channel number: 0~3.
[in] u8FilterValue fliter cycles:1~15, 0: disable channel filter.
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_InputCaptureFilterClr.
References FTM_InputCaptureFilterClr().
void FTM_FaultPinEnable (FTM_Type * pFTM, uint8_t u8FaultPin)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] u8FaultPin the fault input channel number: 0~3.
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_FaultPinDisable.
References FTM_WriteProtectionDisable(), and FTM_WriteProtectionEnable().
void FTM_FaultPinDisable (FTM_Type * pFTM, uint8_t u8FaultPin)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] u8FaultPin the fault input channel number: 0~3.
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_FaultPinEnable.
References FTM_WriteProtectionDisable(), and FTM_WriteProtectionEnable().
void FTM_FaultPinFilterEnable (FTM_Type * pFTM, uint8_t u8FaultPin)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] u8FaultPin the fault input channel number: 0~3.
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_FaultPinFilterDisable.
References FTM_WriteProtectionDisable(), and FTM_WriteProtectionEnable().
void FTM_FaultPinFilterDisable (FTM_Type * pFTM, uint8_t u8FaultPin)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] u8FaultPin the fault input channel number: 0~3.
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_FaultPinFilterDisable.
References FTM_WriteProtectionDisable(), and FTM_WriteProtectionEnable().
void FTM_FaultPinFilterCDisableAll (FTM_Type * pFTM)
Parameters
[in] pFTM pointer to one of three FTM base register address.
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_FaultPinFilterSet.
void FTM_FaultPinFilterSet (FTM_Type * pFTM, uint8_t u8FilterValue)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] u8FilterValue the fault input filter value: 1~15, 0 disable the filter.
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_FaultPinFilterCDisableAll.
References FTM_FaultPinFilterCDisableAll().
uint8_t FTM_GetFaultDetectionLogicORFlag (FTM_Type * pFTM)
Parameters
[in] pFTM pointer to one of three FTM base register address.
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_GetFaultDetectionFlag.
uint8_t FTM_GetFaultDetectionFlag (FTM_Type * pFTM, uint8_t u8FaultPin)
Parameters
[in] pFTM pointer to one of three FTM base register address.
[in] u8FaultPin fault input pin number: 0~3.
Returns
none.
@ Pass/ Fail criteria: none.
See Also
FTM_GetFaultDetectionLogicORFlag.
uint8_t FTM_GetFaultInputsLogicORValue (FTM_Type * pFTM)
Parameters
[in] pFTM pointer to one of three FTM base register address.
Returns
none.
@ Pass/ Fail criteria: none.