Kinetis E Peripheral Drivers: PWT API Specification
PWT API Specification
PWT Driver
Functions
void PWT_Init (PWT_ConfigType *pConfig)
initialize pwt module.
void PWT_SetCallback (PWT_CallbackType pfnCallback)
pwt module set call back.
void PWT_DeInit (void)
pwt module de-initialize, reset pwt register
__STATIC_INLINE void PWT_Enable (void)
enable pwt module.
__STATIC_INLINE void PWT_Disable (void)
disable pwt module.
__STATIC_INLINE void PWT_EnableInt (void)
enable pwt module interrupt.
__STATIC_INLINE void PWT_DisableInt (void)
disable pwt module interrupt .
__STATIC_INLINE void PWT_EnableOverFlowInt (void)
enable pwt module timer over flow interrupt.
__STATIC_INLINE void PWT_DisableOverFlowInt (void)
disable pwt module timer over flow interrupt.
__STATIC_INLINE void PWT_EnableReadyInt (void)
enable pwt module data ready interrupt.
__STATIC_INLINE void PWT_DisableReadyInt (void)
disable pwt module data ready interrupt.
__STATIC_INLINE void PWT_SetSoftReset (void)
set pwt module soft reset.
__STATIC_INLINE void PWT_SetPinSelect (uint8_t u8PinSelect)
set pwt module input pin selct.
__STATIC_INLINE void PWT_SetEdgeSensitivity (uint8_t u8EdgeSensitivity)
set pwt module input edge sensitivity.
__STATIC_INLINE void PWT_SetClockPresacler (uint8_t u8ClockPresacler)
set pwt module input clock presacler.
__STATIC_INLINE uint8_t PWT_GetOverflowFlag (void)
get pwt overflow flag.
__STATIC_INLINE void PWT_ClrOverflowFlag (void)
clear pwt overflow flag.
__STATIC_INLINE uint8_t PWT_GetReadyFlag (void)
get pwt ready flag.
__STATIC_INLINE void PWT_ClrReadyFlag (void)
clear pwt ready flag.
Detailed Description
This section specifies the exact usage for each API function and macro.
inline functions
Function Documentation
void PWT_Init (PWT_ConfigType * pConfig)
Parameters
[in] u8Channel_No channel number
[in] pConfig point to configuration
Returns
none
@ Pass/ Fail criteria: none
References PWT_ConfigType::bClockPrescaler, PWT_ConfigType::bClockSource, PWT_ConfigType::bEdgeSensitivity, PWT_ConfigType::bOverflowIntEn, PWT_ConfigType::bPinSelect, PWT_ConfigType::bPWTEn, PWT_ConfigType::bPWTIntEn, PWT_ConfigType::bReadyIntEn, PWT_ClrOverflowFlag(), PWT_ClrReadyFlag(), PWT_GetOverflowFlag(), and PWT_GetReadyFlag().
void PWT_SetCallback (PWT_CallbackType pfnCallback)
Parameters
[in] u8Channel_No channel number.
[in] pfnCallback point to call back.
Returns
none
@ Pass/ Fail criteria: none
void PWT_DeInit (void)
Parameters
none
Returns
none
@ Pass/ Fail criteria: none
References PWT_Disable(), PWT_DisableInt(), PWT_DisableOverFlowInt(), PWT_DisableReadyInt(), PWT_SetClockPresacler(), PWT_SetEdgeSensitivity(), and PWT_SetSoftReset().
__STATIC_INLINE void PWT_Enable (void)
Parameters
none
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void PWT_Disable (void)
Parameters
none
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void PWT_EnableInt (void)
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void PWT_DisableInt (void)
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void PWT_EnableOverFlowInt (void)
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void PWT_DisableOverFlowInt (void)
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void PWT_EnableReadyInt (void)
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void PWT_DisableReadyInt (void)
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void PWT_SetSoftReset (void)
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void PWT_SetPinSelect (uint8_t u8PinSelect)
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void PWT_SetEdgeSensitivity (uint8_t u8EdgeSensitivity)
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void PWT_SetClockPresacler (uint8_t u8ClockPresacler)
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t PWT_GetOverflowFlag (void)
Returns
bOverflowflag.
@ Pass/ Fail criteria: none
__STATIC_INLINE void PWT_ClrOverflowFlag (void)
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t PWT_GetReadyFlag (void)
Returns
bflag.
@ Pass/ Fail criteria: none
__STATIC_INLINE void PWT_ClrReadyFlag (void)
@ Pass/ Fail criteria: none