Kinetis E Peripheral Drivers: SPI API Specification
SPI API Specification
SPI Driver
Functions
void SPI_Init (SPI_Type *pSPI, SPI_ConfigType *pConfig)
initialize SPI as per params.
void SPI_SetBaudRate (SPI_Type *pSPI, uint32_t u32BusClock, uint32_t u32Bps)
SPI set band rate.
ResultType SPI_TransferWait (SPI_Type *pSPI, SPI_WidthType *pRdBuff, SPI_WidthType *pWrBuff, uint32 uiLength)
implement write data to SPI.
void SPI_DeInit (SPI_Type *pSPI)
Deinitialize SPI to the default state (reset value).
void SPI_SetCallback (SPI_Type *pSPI, SPI_CallbackType pfnCallback)
set up SPI callback routines to be called by interrupt service routine.
__STATIC_INLINE void SPI_SetLSBFirst (SPI_Type *pSPI)
LSB first (shifter direction).
__STATIC_INLINE void SPI_SetMSBFirst (SPI_Type *pSPI)
MSB first (shifter direction).
__STATIC_INLINE void SPI_SetClockPol (SPI_Type *pSPI, uint8_t u8PolLow)
set SPI clock polarity.
__STATIC_INLINE void SPI_SetClockPhase (SPI_Type *pSPI, uint8_t u8Phase)
set SPI clock phase.
__STATIC_INLINE void SPI_Enable (SPI_Type *pSPI)
enable SPI module.
__STATIC_INLINE void SPI_Disable (SPI_Type *pSPI)
disable SPI module.
__STATIC_INLINE void SPI_IntEnable (SPI_Type *pSPI)
enable SPI interrupt.
__STATIC_INLINE void SPI_IntDisable (SPI_Type *pSPI)
disable SPI interrupt.
__STATIC_INLINE void SPI_SetMasterMode (SPI_Type *pSPI)
set SPI to master mode.
__STATIC_INLINE void SPI_SetSlaveMode (SPI_Type *pSPI)
set SPI to slave mode.
__STATIC_INLINE void SPI_TxIntEnable (SPI_Type *pSPI)
SPI transmit interrupt enable.
__STATIC_INLINE void SPI_TxIntDisable (SPI_Type *pSPI)
SPI transmit interrupt disable.
__STATIC_INLINE void SPI_SSOutputEnable (SPI_Type *pSPI)
Slave select output enable.
__STATIC_INLINE void SPI_SSOutputDisable (SPI_Type *pSPI)
Slave select output disable.
__STATIC_INLINE void SPI_MatchIntEnable (SPI_Type *pSPI)
SPI match interrupt enable.
__STATIC_INLINE void SPI_MatchIntDisable (SPI_Type *pSPI)
SPI match interrupt disable.
__STATIC_INLINE void SPI_ModfDisable (SPI_Type *pSPI)
Master mode-fault function disable.
__STATIC_INLINE void SPI_ModfEnable (SPI_Type *pSPI)
Master mode-fault function enable.
__STATIC_INLINE void SPI_BidirOutEnable (SPI_Type *pSPI)
Bidirectional mode output enable.
__STATIC_INLINE void SPI_BidirOutDisable (SPI_Type *pSPI)
Bidirectional mode output disable.
__STATIC_INLINE void SPI_ClockStopDisable (SPI_Type *pSPI)
SPI stop in wait mode.
__STATIC_INLINE void SPI_ClockStopEnable (SPI_Type *pSPI)
SPI stop in wait mode.
__STATIC_INLINE void SPI_BidirPinEnable (SPI_Type *pSPI)
enables bidirectional pin configurations.
__STATIC_INLINE void SPI_BidirPinDisable (SPI_Type *pSPI)
enables bidirectional pin configurations.
__STATIC_INLINE uint8_t SPI_IsSPRF (SPI_Type *pSPI)
check SPI read buffer full flag.
__STATIC_INLINE uint8_t SPI_IsSPMF (SPI_Type *pSPI)
check SPI match flag.
__STATIC_INLINE uint8_t SPI_IsSPTEF (SPI_Type *pSPI)
check SPI transmit buffer empty flag.
__STATIC_INLINE uint8_t SPI_IsMODF (SPI_Type *pSPI)
check master mode fault flag.
__STATIC_INLINE uint8_t SPI_ReadDataReg (SPI_Type *pSPI)
read SPI data register.
__STATIC_INLINE void SPI_WriteDataReg (SPI_Type *pSPI, uint8_t u8WrBuff)
write SPI data register.
__STATIC_INLINE void SPI_WriteMatchValue (SPI_Type *pSPI, uint8_t u8WrBuff)
write SPI match register.
Detailed Description
This section specifies the exact usage for each API function and macro.
Function Documentation
void SPI_Init (SPI_Type * pSPI, SPI_ConfigType * pConfig)
Parameters
[in] pSPI point to SPI module type.
[in] pConfig point to configuration parameters.
Returns
none.
@ Pass/ Fail criteria: none.
References SPI_SettingType::bBidirectionModeEn, SPI_SettingType::bClkPhase1, SPI_SettingType::bClkPolarityLow, SPI_SettingType::bIntEn, SPI_SettingType::bMasterAutoDriveSS, SPI_SettingType::bMasterMode, SPI_SettingType::bMatchIntEn, SPI_SettingType::bModeFaultEn, SPI_SettingType::bModuleEn, SPI_SettingType::bPinAsOuput, SPI_SettingType::bShiftLSBFirst, SPI_SettingType::bStopInWaitMode, SPI_SettingType::bTxIntEn, SPI_BidirOutEnable(), SPI_BidirPinEnable(), SPI_ClockStopEnable(), SPI_Enable(), SPI_IntEnable(), SPI_MatchIntEnable(), SPI_ModfEnable(), SPI_SetBaudRate(), SPI_SetClockPhase(), SPI_SetClockPol(), SPI_SetLSBFirst(), SPI_SetMasterMode(), SPI_SetSlaveMode(), SPI_SSOutputEnable(), SPI_TxIntEnable(), SPI_ConfigType::sSettings, SPI_ConfigType::u32BitRate, and SPI_ConfigType::u32BusClkHz.
void SPI_SetBaudRate (SPI_Type * pSPI, uint32_t u32BusClock, uint32_t u32Bps)
Parameters
[in] pSPI point to SPI module type.
[in] u32BusClock Bus clock.
[in] u32Bps set spi's baudrate.
Returns
none.
@ Pass/ Fail criteria: none.
ResultType SPI_TransferWait (SPI_Type * pSPI, SPI_WidthType * pRdBuff, SPI_WidthType * pWrBuff, uint32 uiLength)
Parameters
[in] pSPI pointer to SPI module type.
[in] pWrBuff – write data buffer pointer.
[in] uiLength – read/write data length.
[out] pRdBuff – read data buffer pointer.
Returns
if <0, means error, 0: success.
@ Pass/ Fail criteria: none.
References SPI_ERR_SUCCESS, SPI_IsSPRF(), SPI_IsSPTEF(), SPI_ReadDataReg(), and SPI_WriteDataReg().
void SPI_DeInit (SPI_Type * pSPI)
Parameters
[in] pSPI pointer to SPI module type.
Returns
none.
@ Pass/ Fail criteria: none.
References SPI_BR_DEFAULT, SPI_C1_DEFAULT, SPI_C2_DEFAULT, and SPI_M_DEFAULT.
void SPI_SetCallback (SPI_Type * pSPI, SPI_CallbackType pfnCallback)
Parameters
[in] pSPI pointer to SPI module type.
[in] pfnCallback callback routine.
Returns
none.
@ Pass/ Fail criteria: none.
void SPI_SetLSBFirst (SPI_Type * pSPI)
Parameters
[in] pSPI point to SPI module type.
Returns
none.
@ Pass/ Fail criteria: none.
void SPI_SetMSBFirst (SPI_Type * pSPI)
Parameters
[in] pSPI point to SPI module type.
Returns
none.
@ Pass/ Fail criteria: none.
void SPI_SetClockPol (SPI_Type * pSPI, uint8_t u8PolLow)
Parameters
[in] pSPI point to SPI module type.
[in] u8PolLow set clock polarity, 1 - Active-low SPI clock (idles high).
Returns
none
@ Pass/ Fail criteria: none
void SPI_SetClockPhase (SPI_Type * pSPI, uint8_t u8Phase)
Parameters
[in] pSPI point to SPI module type.
[in] u8Phase set clock phase, 1 - First edge on SPSCK occurs at the start of the first cycle of a data transfer.
Returns
none
@ Pass/ Fail criteria: none
void SPI_Enable (SPI_Type * pSPI)
Parameters
[in] pSPI point to SPI module type.
Returns
none
@ Pass/ Fail criteria: none
void SPI_Disable (SPI_Type * pSPI)
Parameters
[in] pSPI point to SPI module type.
Returns
none
@ Pass/ Fail criteria: none
void SPI_IntEnable (SPI_Type * pSPI)
Parameters
[in] pSPI point to SPI module type.
Returns
none
@ Pass/ Fail criteria: none
void SPI_IntDisable (SPI_Type * pSPI)
Parameters
[in] pSPI point to SPI module type.
Returns
none
@ Pass/ Fail criteria: none
void SPI_SetMasterMode (SPI_Type * pSPI)
Parameters
[in] pSPI point to SPI module type.
Returns
none
@ Pass/ Fail criteria: none
void SPI_SetSlaveMode (SPI_Type * pSPI)
Parameters
[in] pSPI point to SPI module type.
Returns
none
@ Pass/ Fail criteria: none
void SPI_TxIntEnable (SPI_Type * pSPI)
Parameters
[in] pSPI point to SPI module type.
Returns
none.
@ Pass/ Fail criteria: none.
void SPI_TxIntDisable (SPI_Type * pSPI)
Parameters
[in] pSPI point to SPI module type.
Returns
none
@ Pass/ Fail criteria: none
void SPI_SSOutputEnable (SPI_Type * pSPI)
Parameters
[in] pSPI point to SPI module type.
Returns
none
@ Pass/ Fail criteria: none
void SPI_SSOutputDisable (SPI_Type * pSPI)
Parameters
[in] pSPI point to SPI module type.
Returns
none
@ Pass/ Fail criteria: none
void SPI_MatchIntEnable (SPI_Type * pSPI)
Parameters
[in] pSPI point to SPI module type.
Returns
none
@ Pass/ Fail criteria: none
void SPI_MatchIntDisable (SPI_Type * pSPI)
Parameters
[in] pSPI point to SPI module type.
Returns
none.
@ Pass/ Fail criteria: none.
void SPI_ModfDisable (SPI_Type * pSPI)
Parameters
[in] pSPI point to SPI module type.
Returns
none.
@ Pass/ Fail criteria: none.
void SPI_ModfEnable (SPI_Type * pSPI)
Parameters
[in] pSPI point to SPI module type.
Returns
none.
@ Pass/ Fail criteria: none.
void SPI_BidirOutEnable (SPI_Type * pSPI)
Parameters
[in] pSPI point to SPI module type.
Returns
none.
@ Pass/ Fail criteria: none.
void SPI_BidirOutDisable (SPI_Type * pSPI)
Parameters
[in] pSPI point to SPI module type.
Returns
none.
@ Pass/ Fail criteria: none.
void SPI_ClockStopDisable (SPI_Type * pSPI)
Parameters
[in] pSPI point to SPI module type.
Returns
none.
@ Pass/ Fail criteria: none.
void SPI_ClockStopEnable (SPI_Type * pSPI)
Parameters
[in] pSPI point to SPI module type.
Returns
none
@ Pass/ Fail criteria: none
void SPI_BidirPinEnable (SPI_Type * pSPI)
Parameters
[in] pSPI point to SPI module type.
Returns
none
@ Pass/ Fail criteria: none
void SPI_BidirPinDisable (SPI_Type * pSPI)
Parameters
[in] pSPI point to SPI module type.
Returns
none
@ Pass/ Fail criteria: none
uint8_t SPI_IsSPRF (SPI_Type * pSPI)
Parameters
[in] pSPI point to SPI module type.
Returns
TRUE or FALSE.
@ Pass/ Fail criteria: none.
uint8_t SPI_IsSPMF (SPI_Type * pSPI)
Parameters
[in] pSPI point to SPI module type.
Returns
TRUE or FALSE.
@ Pass/ Fail criteria: none.
uint8_t SPI_IsSPTEF (SPI_Type * pSPI)
Parameters
[in] pSPI point to SPI module type.
Returns
TRUE or FALSE.
@ Pass/ Fail criteria: none
uint8_t SPI_IsMODF (SPI_Type * pSPI)
Parameters
[in] pSPI point to SPI module type.
Returns
TRUE or FALSE.
@ Pass/ Fail criteria: none
uint8_t SPI_ReadDataReg (SPI_Type * pSPI)
Parameters
[in] pSPI point to SPI module type.
Returns
data register value
@ Pass/ Fail criteria: none
void SPI_WriteDataReg (SPI_Type * pSPI, uint8_t u8WrBuff)
Parameters
[in] pSPI point to SPI module type.
[in] u8WrBuff data buffer write to spi data register.
Returns
none
@ Pass/ Fail criteria: none
void SPI_WriteMatchValue (SPI_Type * pSPI, uint8_t u8WrBuff)
Parameters
[in] pSPI point to SPI module type.
[in] u8WrBuff the data buffer write to match register.
Returns
none
@ Pass/ Fail criteria: none