Kinetis E Peripheral Drivers: PIT API Specification
PIT API Specification
PIT Driver
Functions
void PIT_Init (uint8_t u8Channel_No, PIT_ConfigType *pConfig)
initialize pit module.
void PIT_SetLoadVal (uint8_t u8Channel, uint32_t u32loadvalue)
initialize pit module.
void PIT_SetCallback (uint8_t u8Channel_No, PIT_CallbackType pfnCallback)
pit module set call back.
void PIT_DeInit (void)
pit module de-initialize, reset pit register
__STATIC_INLINE void PIT_Enable (void)
enable pit module.
__STATIC_INLINE void PIT_Disable (void)
disable pit module.
__STATIC_INLINE void PIT_SetDebugFreeze (void)
pit timers are stopped in debug mode.
__STATIC_INLINE void PIT_SetDebugOn (void)
pit timers are running in debug mode.
__STATIC_INLINE void PIT_ChannelEnable (uint8_t u8Channel)
enable pit channel timer.
__STATIC_INLINE void PIT_ChannelDisable (uint8_t u8Channel)
disable pit channel timer.
__STATIC_INLINE void PIT_ChannelEnableInt (uint8_t u8Channel)
enable pit channel timer interrupt.
__STATIC_INLINE void PIT_ChannelDisableInt (uint8_t u8Channel)
disable pit channel timer interrupt .
__STATIC_INLINE void PIT_ChannelEnableChain (uint8_t u8Channel)
enable pit channel timer chain mode.
__STATIC_INLINE void PIT_ChannelDisableChain (uint8_t u8Channel)
disable pit channel timer chain mode.
__STATIC_INLINE uint8_t PIT_ChannelGetFlags (uint8_t u8Channel)
get pit channel timer interrrupt flag.
__STATIC_INLINE void PIT_ChannelClrFlags (uint8_t u8Channel)
clear pit channel timer interrrupt flag.
Detailed Description
This section specifies the exact usage for each API function and macro.
inline functions
Function Documentation
void PIT_Init (uint8_t u8Channel_No, PIT_ConfigType * pConfig)
Parameters
[in] u8Channel_No channel number
[in] pConfig point to configuration
Returns
none
@ Pass/ Fail criteria: none
References PIT_ConfigType::bChainMode, PIT_ConfigType::bFreeze, PIT_ConfigType::bInterruptEn, PIT_ConfigType::bModuleDis, PIT_ConfigType::bTimerEn, PIT_ChannelEnable(), PIT_ChannelEnableChain(), PIT_ChannelEnableInt(), PIT_Enable(), PIT_SetDebugFreeze(), PIT_SetLoadVal(), and PIT_ConfigType::u32LoadValue.
void PIT_SetLoadVal (uint8_t u8Channel, uint32_t u32loadvalue)
Parameters
[in] u8Channel_No channel number
[in] u32loadvalue load value for pit register
Returns
none
@ Pass/ Fail criteria: none
void PIT_SetCallback (uint8_t u8Channel_No, PIT_CallbackType pfnCallback)
Parameters
[in] u8Channel_No channel number.
[in] pfnCallback point to call back.
Returns
none
@ Pass/ Fail criteria: none
void PIT_DeInit (void)
Parameters
none
Returns
none
@ Pass/ Fail criteria: none
References PIT_ChannelClrFlags(), PIT_ChannelDisable(), PIT_ChannelDisableChain(), PIT_ChannelDisableInt(), PIT_Disable(), PIT_SetDebugOn(), and PIT_SetLoadVal().
__STATIC_INLINE void PIT_Enable (void)
Parameters
none
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void PIT_Disable (void)
Parameters
none
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void PIT_SetDebugFreeze (void)
Parameters
none
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void PIT_SetDebugOn (void)
Parameters
none
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void PIT_ChannelEnable (uint8_t u8Channel)
Parameters
[in] u8Channel.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void PIT_ChannelDisable (uint8_t u8Channel)
Parameters
[in] u8Channel.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void PIT_ChannelEnableInt (uint8_t u8Channel)
Parameters
[in] u8Channel.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void PIT_ChannelDisableInt (uint8_t u8Channel)
Parameters
[in] u8Channel.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void PIT_ChannelEnableChain (uint8_t u8Channel)
Parameters
[in] u8Channel.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE void PIT_ChannelDisableChain (uint8_t u8Channel)
Parameters
[in] u8Channel.
Returns
none
@ Pass/ Fail criteria: none
__STATIC_INLINE uint8_t PIT_ChannelGetFlags (uint8_t u8Channel)
Parameters
[in] u8Channel.
Returns
bflag.
@ Pass/ Fail criteria: none
__STATIC_INLINE void PIT_ChannelClrFlags (uint8_t u8Channel)
Parameters
[in] u8Channel
Returns
none
@ Pass/ Fail criteria: none